
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)

interface _GlobalComponents {
      'Breadcrumb': typeof import("../../components/ui/breadcrumb/Breadcrumb.vue")['default']
    'BreadcrumbEllipsis': typeof import("../../components/ui/breadcrumb/BreadcrumbEllipsis.vue")['default']
    'BreadcrumbItem': typeof import("../../components/ui/breadcrumb/BreadcrumbItem.vue")['default']
    'BreadcrumbLink': typeof import("../../components/ui/breadcrumb/BreadcrumbLink.vue")['default']
    'BreadcrumbList': typeof import("../../components/ui/breadcrumb/BreadcrumbList.vue")['default']
    'BreadcrumbPage': typeof import("../../components/ui/breadcrumb/BreadcrumbPage.vue")['default']
    'BreadcrumbSeparator': typeof import("../../components/ui/breadcrumb/BreadcrumbSeparator.vue")['default']
    'Button': typeof import("../../components/ui/button/Button.vue")['default']
    'Calendar': typeof import("../../components/ui/calendar/Calendar.vue")['default']
    'CalendarCell': typeof import("../../components/ui/calendar/CalendarCell.vue")['default']
    'CalendarCellTrigger': typeof import("../../components/ui/calendar/CalendarCellTrigger.vue")['default']
    'CalendarGrid': typeof import("../../components/ui/calendar/CalendarGrid.vue")['default']
    'CalendarGridBody': typeof import("../../components/ui/calendar/CalendarGridBody.vue")['default']
    'CalendarGridHead': typeof import("../../components/ui/calendar/CalendarGridHead.vue")['default']
    'CalendarGridRow': typeof import("../../components/ui/calendar/CalendarGridRow.vue")['default']
    'CalendarHeadCell': typeof import("../../components/ui/calendar/CalendarHeadCell.vue")['default']
    'CalendarHeader': typeof import("../../components/ui/calendar/CalendarHeader.vue")['default']
    'CalendarHeading': typeof import("../../components/ui/calendar/CalendarHeading.vue")['default']
    'CalendarNextButton': typeof import("../../components/ui/calendar/CalendarNextButton.vue")['default']
    'CalendarPrevButton': typeof import("../../components/ui/calendar/CalendarPrevButton.vue")['default']
    'Card': typeof import("../../components/ui/card/Card.vue")['default']
    'CardAction': typeof import("../../components/ui/card/CardAction.vue")['default']
    'CardContent': typeof import("../../components/ui/card/CardContent.vue")['default']
    'CardDescription': typeof import("../../components/ui/card/CardDescription.vue")['default']
    'CardFooter': typeof import("../../components/ui/card/CardFooter.vue")['default']
    'CardHeader': typeof import("../../components/ui/card/CardHeader.vue")['default']
    'CardTitle': typeof import("../../components/ui/card/CardTitle.vue")['default']
    'Checkbox': typeof import("../../components/ui/checkbox/Checkbox.vue")['default']
    'Combobox': typeof import("../../components/ui/combobox/Combobox.vue")['default']
    'ComboboxAnchor': typeof import("../../components/ui/combobox/ComboboxAnchor.vue")['default']
    'ComboboxEmpty': typeof import("../../components/ui/combobox/ComboboxEmpty.vue")['default']
    'ComboboxGroup': typeof import("../../components/ui/combobox/ComboboxGroup.vue")['default']
    'ComboboxInput': typeof import("../../components/ui/combobox/ComboboxInput.vue")['default']
    'ComboboxItem': typeof import("../../components/ui/combobox/ComboboxItem.vue")['default']
    'ComboboxItemIndicator': typeof import("../../components/ui/combobox/ComboboxItemIndicator.vue")['default']
    'ComboboxList': typeof import("../../components/ui/combobox/ComboboxList.vue")['default']
    'ComboboxSeparator': typeof import("../../components/ui/combobox/ComboboxSeparator.vue")['default']
    'ComboboxTrigger': typeof import("../../components/ui/combobox/ComboboxTrigger.vue")['default']
    'ComboboxViewport': typeof import("../../components/ui/combobox/ComboboxViewport.vue")['default']
    'Command': typeof import("../../components/ui/command/Command.vue")['default']
    'CommandDialog': typeof import("../../components/ui/command/CommandDialog.vue")['default']
    'CommandEmpty': typeof import("../../components/ui/command/CommandEmpty.vue")['default']
    'CommandGroup': typeof import("../../components/ui/command/CommandGroup.vue")['default']
    'CommandInput': typeof import("../../components/ui/command/CommandInput.vue")['default']
    'CommandItem': typeof import("../../components/ui/command/CommandItem.vue")['default']
    'CommandList': typeof import("../../components/ui/command/CommandList.vue")['default']
    'CommandSeparator': typeof import("../../components/ui/command/CommandSeparator.vue")['default']
    'CommandShortcut': typeof import("../../components/ui/command/CommandShortcut.vue")['default']
    'Dialog': typeof import("../../components/ui/dialog/Dialog.vue")['default']
    'DialogClose': typeof import("../../components/ui/dialog/DialogClose.vue")['default']
    'DialogContent': typeof import("../../components/ui/dialog/DialogContent.vue")['default']
    'DialogDescription': typeof import("../../components/ui/dialog/DialogDescription.vue")['default']
    'DialogFooter': typeof import("../../components/ui/dialog/DialogFooter.vue")['default']
    'DialogHeader': typeof import("../../components/ui/dialog/DialogHeader.vue")['default']
    'DialogOverlay': typeof import("../../components/ui/dialog/DialogOverlay.vue")['default']
    'DialogScrollContent': typeof import("../../components/ui/dialog/DialogScrollContent.vue")['default']
    'DialogTitle': typeof import("../../components/ui/dialog/DialogTitle.vue")['default']
    'DialogTrigger': typeof import("../../components/ui/dialog/DialogTrigger.vue")['default']
    'DropdownMenu': typeof import("../../components/ui/dropdown-menu/DropdownMenu.vue")['default']
    'DropdownMenuCheckboxItem': typeof import("../../components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']
    'DropdownMenuContent': typeof import("../../components/ui/dropdown-menu/DropdownMenuContent.vue")['default']
    'DropdownMenuGroup': typeof import("../../components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']
    'DropdownMenuItem': typeof import("../../components/ui/dropdown-menu/DropdownMenuItem.vue")['default']
    'DropdownMenuLabel': typeof import("../../components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']
    'DropdownMenuRadioGroup': typeof import("../../components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']
    'DropdownMenuRadioItem': typeof import("../../components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']
    'DropdownMenuSeparator': typeof import("../../components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']
    'DropdownMenuShortcut': typeof import("../../components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']
    'DropdownMenuSub': typeof import("../../components/ui/dropdown-menu/DropdownMenuSub.vue")['default']
    'DropdownMenuSubContent': typeof import("../../components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']
    'DropdownMenuSubTrigger': typeof import("../../components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']
    'DropdownMenuTrigger': typeof import("../../components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']
    'FormControl': typeof import("../../components/ui/form/FormControl.vue")['default']
    'FormDescription': typeof import("../../components/ui/form/FormDescription.vue")['default']
    'FormItem': typeof import("../../components/ui/form/FormItem.vue")['default']
    'FormLabel': typeof import("../../components/ui/form/FormLabel.vue")['default']
    'FormMessage': typeof import("../../components/ui/form/FormMessage.vue")['default']
    'Form': typeof import("../../components/ui/form/index")['default']
    'FormInjectionKeys': typeof import("../../components/ui/form/injectionKeys")['default']
    'FormUseFormField': typeof import("../../components/ui/form/useFormField")['default']
    'Input': typeof import("../../components/ui/input/Input.vue")['default']
    'Label': typeof import("../../components/ui/label/Label.vue")['default']
    'Popover': typeof import("../../components/ui/popover/Popover.vue")['default']
    'PopoverAnchor': typeof import("../../components/ui/popover/PopoverAnchor.vue")['default']
    'PopoverContent': typeof import("../../components/ui/popover/PopoverContent.vue")['default']
    'PopoverTrigger': typeof import("../../components/ui/popover/PopoverTrigger.vue")['default']
    'Select': typeof import("../../components/ui/select/Select.vue")['default']
    'SelectContent': typeof import("../../components/ui/select/SelectContent.vue")['default']
    'SelectGroup': typeof import("../../components/ui/select/SelectGroup.vue")['default']
    'SelectItem': typeof import("../../components/ui/select/SelectItem.vue")['default']
    'SelectItemText': typeof import("../../components/ui/select/SelectItemText.vue")['default']
    'SelectLabel': typeof import("../../components/ui/select/SelectLabel.vue")['default']
    'SelectScrollDownButton': typeof import("../../components/ui/select/SelectScrollDownButton.vue")['default']
    'SelectScrollUpButton': typeof import("../../components/ui/select/SelectScrollUpButton.vue")['default']
    'SelectSeparator': typeof import("../../components/ui/select/SelectSeparator.vue")['default']
    'SelectTrigger': typeof import("../../components/ui/select/SelectTrigger.vue")['default']
    'SelectValue': typeof import("../../components/ui/select/SelectValue.vue")['default']
    'Skeleton': typeof import("../../components/ui/skeleton/Skeleton.vue")['default']
    'Sonner': typeof import("../../components/ui/sonner/Sonner.vue")['default']
    'Table': typeof import("../../components/ui/table/Table.vue")['default']
    'TableBody': typeof import("../../components/ui/table/TableBody.vue")['default']
    'TableCaption': typeof import("../../components/ui/table/TableCaption.vue")['default']
    'TableCell': typeof import("../../components/ui/table/TableCell.vue")['default']
    'TableEmpty': typeof import("../../components/ui/table/TableEmpty.vue")['default']
    'TableFooter': typeof import("../../components/ui/table/TableFooter.vue")['default']
    'TableHead': typeof import("../../components/ui/table/TableHead.vue")['default']
    'TableHeader': typeof import("../../components/ui/table/TableHeader.vue")['default']
    'TableRow': typeof import("../../components/ui/table/TableRow.vue")['default']
    'TableUtils': typeof import("../../components/ui/table/utils")['default']
    'Tabs': typeof import("../../components/ui/tabs/Tabs.vue")['default']
    'TabsContent': typeof import("../../components/ui/tabs/TabsContent.vue")['default']
    'TabsList': typeof import("../../components/ui/tabs/TabsList.vue")['default']
    'TabsTrigger': typeof import("../../components/ui/tabs/TabsTrigger.vue")['default']
    'Textarea': typeof import("../../components/ui/textarea/Textarea.vue")['default']
    'Tooltip': typeof import("../../components/ui/tooltip/Tooltip.vue")['default']
    'TooltipContent': typeof import("../../components/ui/tooltip/TooltipContent.vue")['default']
    'TooltipProvider': typeof import("../../components/ui/tooltip/TooltipProvider.vue")['default']
    'TooltipTrigger': typeof import("../../components/ui/tooltip/TooltipTrigger.vue")['default']
    'AdminDashboardAdminStatsCards': typeof import("../../components/admin/dashboard/AdminStatsCards.vue")['default']
    'AdminDashboardAdminWelcomeHeader': typeof import("../../components/admin/dashboard/AdminWelcomeHeader.vue")['default']
    'AdminDashboardAnalyticsChart': typeof import("../../components/admin/dashboard/AnalyticsChart.vue")['default']
    'AdminDashboardSystemMetrics': typeof import("../../components/admin/dashboard/SystemMetrics.vue")['default']
    'AdminDashboardUserManagement': typeof import("../../components/admin/dashboard/UserManagement.vue")['default']
    'AppFormTypedCheckbox': typeof import("../../components/app/form/TypedCheckbox.vue")['default']
    'AppFormTypedCombobox': typeof import("../../components/app/form/TypedCombobox.vue")['default']
    'AppFormTypedDate': typeof import("../../components/app/form/TypedDate.vue")['default']
    'AppFormTypedDatetime': typeof import("../../components/app/form/TypedDatetime.vue")['default']
    'AppFormTypedFile': typeof import("../../components/app/form/TypedFile.vue")['default']
    'AppFormTypedForm': typeof import("../../components/app/form/TypedForm.vue")['default']
    'AppFormTypedInput': typeof import("../../components/app/form/TypedInput.vue")['default']
    'AppFormTypedNumber': typeof import("../../components/app/form/TypedNumber.vue")['default']
    'AppFormTypedSelect': typeof import("../../components/app/form/TypedSelect.vue")['default']
    'AppFormTypedTextarea': typeof import("../../components/app/form/TypedTextarea.vue")['default']
    'AppFormTypedTime': typeof import("../../components/app/form/TypedTime.vue")['default']
    'AppForm': typeof import("../../components/app/form/index")['default']
    'AppICDBrowser': typeof import("../../components/app/icd/ICDBrowser.client.vue")['default']
    'AppIcd': typeof import("../../components/app/icd/index")['default']
    'AppOCRCanvas': typeof import("../../components/app/ocr/OCRCanvas.vue")['default']
    'AppOCRDialog': typeof import("../../components/app/ocr/OCRDialog.vue")['default']
    'AppOcr': typeof import("../../components/app/ocr/index")['default']
    'AppQrcodeQRCodeDisplay': typeof import("../../components/app/qrcode/QRCodeDisplay.vue")['default']
    'AppQrcodeQRCodeScanner': typeof import("../../components/app/qrcode/QRCodeScanner.vue")['default']
    'AppQrcode': typeof import("../../components/app/qrcode/index")['default']
    'AppReportsLineChartTile': typeof import("../../components/app/reports/LineChartTile.vue")['default']
    'AppReportsNumericTile': typeof import("../../components/app/reports/NumericTile.vue")['default']
    'AppReportsPieChartTile': typeof import("../../components/app/reports/PieChartTile.vue")['default']
    'AppReports': typeof import("../../components/app/reports/index")['default']
    'LayoutBreadcrumbsPageBreadcrumbs': typeof import("../../components/layout/breadcrumbs/PageBreadcrumbs.vue")['default']
    'LayoutBreadcrumbs': typeof import("../../components/layout/breadcrumbs/index")['default']
    'LayoutCommandDialog': typeof import("../../components/layout/command/CommandDialog.vue")['default']
    'LayoutCommandGroup': typeof import("../../components/layout/command/CommandGroup.vue")['default']
    'LayoutCommandPalette': typeof import("../../components/layout/command/CommandPalette.vue")['default']
    'LayoutCommand': typeof import("../../components/layout/command/index")['default']
    'LayoutNotificationsPopover': typeof import("../../components/layout/notifications/NotificationsPopover.vue")['default']
    'LayoutNotifications': typeof import("../../components/layout/notifications/index")['default']
    'LayoutSidebarBase': typeof import("../../components/layout/sidebar/SidebarBase.vue")['default']
    'LayoutSidebarFooter': typeof import("../../components/layout/sidebar/SidebarFooter.vue")['default']
    'LayoutSidebarGroup': typeof import("../../components/layout/sidebar/SidebarGroup.vue")['default']
    'LayoutSidebarHeader': typeof import("../../components/layout/sidebar/SidebarHeader.vue")['default']
    'LayoutSidebarItem': typeof import("../../components/layout/sidebar/SidebarItem.vue")['default']
    'LayoutSidebar': typeof import("../../components/layout/sidebar/index")['default']
    'StaffDashboardAnalyticsChart': typeof import("../../components/staff/dashboard/AnalyticsChart.vue")['default']
    'StaffDashboardRecentActivities': typeof import("../../components/staff/dashboard/RecentActivities.vue")['default']
    'StaffDashboardStatsCards': typeof import("../../components/staff/dashboard/StatsCards.vue")['default']
    'StaffDashboardTodaysAppointments': typeof import("../../components/staff/dashboard/TodaysAppointments.vue")['default']
    'StaffDashboardWelcomeHeader': typeof import("../../components/staff/dashboard/WelcomeHeader.vue")['default']
    'AboutUsForm': typeof import("../../pages/(public)/platform/components/AboutUsForm.vue")['default']
    'EnterpriseForm': typeof import("../../pages/(public)/platform/components/EnterpriseForm.vue")['default']
    'LoginForm': typeof import("../../pages/(public)/platform/components/LoginForm.vue")['default']
    'PrivacyPolicyForm': typeof import("../../pages/(public)/platform/components/PrivacyPolicyForm.vue")['default']
    'ProfessionalForm': typeof import("../../pages/(public)/platform/components/ProfessionalForm.vue")['default']
    'ServicesForm': typeof import("../../pages/(public)/platform/components/ServicesForm.vue")['default']
    'SignUpForm': typeof import("../../pages/(public)/platform/components/SignUpForm.vue")['default']
    'StartUpForm': typeof import("../../pages/(public)/platform/components/StartUpForm.vue")['default']
    'SupportForm': typeof import("../../pages/(public)/platform/components/SupportForm.vue")['default']
    'TermsOfUseForm': typeof import("../../pages/(public)/platform/components/TermsOfUseForm.vue")['default']
    'LogEntityCell': typeof import("../../pages/admin/logs/components/LogEntityCell.vue")['default']
    'LogsTable': typeof import("../../pages/admin/logs/components/LogsTable.vue")['default']
    'UserProfileForm': typeof import("../../pages/admin/users/components/UserProfileForm.vue")['default']
    'IndexDashboard': typeof import("../../pages/index/components/IndexDashboard.vue")['default']
    'ClaimRequestForm': typeof import("../../pages/partner/components/ClaimRequestForm.vue")['default']
    'ClaimRequestsTable': typeof import("../../pages/partner/components/ClaimRequestsTable.vue")['default']
    'DataRequestForm': typeof import("../../pages/partner/components/DataRequestForm.vue")['default']
    'DataRequestsTable': typeof import("../../pages/partner/components/DataRequestsTable.vue")['default']
    'PartnerForm': typeof import("../../pages/partner/components/PartnerForm.vue")['default']
    'PartnerTable': typeof import("../../pages/partner/components/PartnerTable.vue")['default']
    'PatientAppointmentFilters': typeof import("../../pages/patient/appointments/components/PatientAppointmentFilters.vue")['default']
    'PatientAppointmentForm': typeof import("../../pages/patient/appointments/components/PatientAppointmentForm.vue")['default']
    'PatientAppointmentsAvailability': typeof import("../../pages/patient/appointments/components/PatientAppointmentsAvailability.vue")['default']
    'PatientAppointmentsTable': typeof import("../../pages/patient/appointments/components/PatientAppointmentsTable.vue")['default']
    'PatientsBillingTable': typeof import("../../pages/patient/billing/components/PatientsBillingTable.vue")['default']
    'DoctorTable': typeof import("../../pages/patient/doctor/components/DoctorTable.vue")['default']
    'MedicalRecordForm': typeof import("../../pages/patient/medical-records/components/MedicalRecordForm.vue")['default']
    'MedicalRecordsTable': typeof import("../../pages/patient/medical-records/components/MedicalRecordsTable.vue")['default']
    'AppointmentFilters': typeof import("../../pages/staff/appointments/components/AppointmentFilters.vue")['default']
    'AppointmentForm': typeof import("../../pages/staff/appointments/components/AppointmentForm.vue")['default']
    'AppointmentsAvailability': typeof import("../../pages/staff/appointments/components/AppointmentsAvailability.vue")['default']
    'AppointmentsTable': typeof import("../../pages/staff/appointments/components/AppointmentsTable.vue")['default']
    'BillingPaymentForm': typeof import("../../pages/staff/billing/components/BillingPaymentForm.vue")['default']
    'BillingPaymentInstalmentForm': typeof import("../../pages/staff/billing/components/BillingPaymentInstalmentForm.vue")['default']
    'BillingPaymentInstalmentTable': typeof import("../../pages/staff/billing/components/BillingPaymentInstalmentTable.vue")['default']
    'BillingPaymentPlanForm': typeof import("../../pages/staff/billing/components/BillingPaymentPlanForm.vue")['default']
    'BillingPaymentPlansTable': typeof import("../../pages/staff/billing/components/BillingPaymentPlansTable.vue")['default']
    'BillingPaymentsTable': typeof import("../../pages/staff/billing/components/BillingPaymentsTable.vue")['default']
    'BillingTransactionForm': typeof import("../../pages/staff/billing/components/BillingTransactionForm.vue")['default']
    'BillingTransactionItemForm': typeof import("../../pages/staff/billing/components/BillingTransactionItemForm.vue")['default']
    'BillingTransactionItemsTable': typeof import("../../pages/staff/billing/components/BillingTransactionItemsTable.vue")['default']
    'BillingTransactionsTable': typeof import("../../pages/staff/billing/components/BillingTransactionsTable.vue")['default']
    'AppointmentsList': typeof import("../../pages/staff/dashboard/components/AppointmentsList.vue")['default']
    'DashboardFilters': typeof import("../../pages/staff/dashboard/components/DashboardFilters.vue")['default']
    'DashboardSummaryCards': typeof import("../../pages/staff/dashboard/components/DashboardSummaryCards.vue")['default']
    'DoctorDashboard': typeof import("../../pages/staff/dashboard/components/DoctorDashboard.vue")['default']
    'SecretaryDashboard': typeof import("../../pages/staff/dashboard/components/SecretaryDashboard.vue")['default']
    'BuildingForm': typeof import("../../pages/staff/facilities/components/BuildingForm.vue")['default']
    'BuildingsTable': typeof import("../../pages/staff/facilities/components/BuildingsTable.vue")['default']
    'FacilitiesTable': typeof import("../../pages/staff/facilities/components/FacilitiesTable.vue")['default']
    'FacilityForm': typeof import("../../pages/staff/facilities/components/FacilityForm.vue")['default']
    'FacilityLogsTable': typeof import("../../pages/staff/facilities/components/FacilityLogsTable.vue")['default']
    'InsuranceClaimForm': typeof import("../../pages/staff/insurance/components/InsuranceClaimForm.vue")['default']
    'InsuranceClaimItemForm': typeof import("../../pages/staff/insurance/components/InsuranceClaimItemForm.vue")['default']
    'InsuranceClaimItemsTable': typeof import("../../pages/staff/insurance/components/InsuranceClaimItemsTable.vue")['default']
    'InsuranceClaimsTable': typeof import("../../pages/staff/insurance/components/InsuranceClaimsTable.vue")['default']
    'InsuranceProviderForm': typeof import("../../pages/staff/insurance/components/InsuranceProviderForm.vue")['default']
    'InsuranceProviderTable': typeof import("../../pages/staff/insurance/components/InsuranceProviderTable.vue")['default']
    'EncountersModule': typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/EncountersModule.vue")['default']
    'InpatientForm': typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/InpatientForm.vue")['default']
    'OutpatientForm': typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/OutpatientForm.vue")['default']
    'EncountersTable': typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/components/EncountersTable.vue")['default']
    'InpatientTable': typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/components/InpatientTable.vue")['default']
    'OutpatientTable': typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/components/OutpatientTable.vue")['default']
    '[inpatientEncounterId]': typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/inpatient/[inpatientEncounterId].vue")['default']
    '[outpatientEncounterId]': typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/outpatient/[outpatientEncounterId].vue")['default']
    'New': typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/outpatient/new.vue")['default']
    'AddressFields': typeof import("../../pages/staff/patients/components/AddressFields.vue")['default']
    'ConsentFields': typeof import("../../pages/staff/patients/components/ConsentFields.vue")['default']
    'ContactFields': typeof import("../../pages/staff/patients/components/ContactFields.vue")['default']
    'EmergencyContactFields': typeof import("../../pages/staff/patients/components/EmergencyContactFields.vue")['default']
    'EmploymentFields': typeof import("../../pages/staff/patients/components/EmploymentFields.vue")['default']
    'PatientProfileForm': typeof import("../../pages/staff/patients/components/PatientProfileForm.vue")['default']
    'PatientProfileTable': typeof import("../../pages/staff/patients/components/PatientProfileTable.vue")['default']
    'ProfileFields': typeof import("../../pages/staff/patients/components/ProfileFields.vue")['default']
    'PharmacyBrandForm': typeof import("../../pages/staff/pharmacy/components/PharmacyBrandForm.vue")['default']
    'PharmacyBrandsTable': typeof import("../../pages/staff/pharmacy/components/PharmacyBrandsTable.vue")['default']
    'PharmacyCategoriesTable': typeof import("../../pages/staff/pharmacy/components/PharmacyCategoriesTable.vue")['default']
    'PharmacyCategoryForm': typeof import("../../pages/staff/pharmacy/components/PharmacyCategoryForm.vue")['default']
    'PharmacyItemForm': typeof import("../../pages/staff/pharmacy/components/PharmacyItemForm.vue")['default']
    'PharmacyItemsTable': typeof import("../../pages/staff/pharmacy/components/PharmacyItemsTable.vue")['default']
    'PharmacySupplierForm': typeof import("../../pages/staff/pharmacy/components/PharmacySupplierForm.vue")['default']
    'PharmacySuppliersTable': typeof import("../../pages/staff/pharmacy/components/PharmacySuppliersTable.vue")['default']
    'StaffForm': typeof import("../../pages/staff/staff/components/StaffForm.vue")['default']
    'StaffTable': typeof import("../../pages/staff/staff/components/StaffTable.vue")['default']
    'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
    'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'Icon': typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'UiBreadcrumb': typeof import("../../components/ui/breadcrumb/index")['Breadcrumb']
    'UiBreadcrumbEllipsis': typeof import("../../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'UiBreadcrumbItem': typeof import("../../components/ui/breadcrumb/index")['BreadcrumbItem']
    'UiBreadcrumbLink': typeof import("../../components/ui/breadcrumb/index")['BreadcrumbLink']
    'UiBreadcrumbList': typeof import("../../components/ui/breadcrumb/index")['BreadcrumbList']
    'UiBreadcrumbPage': typeof import("../../components/ui/breadcrumb/index")['BreadcrumbPage']
    'UiBreadcrumbSeparator': typeof import("../../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'UiButton': typeof import("../../components/ui/button/index")['Button']
    'UiCalendar': typeof import("../../components/ui/calendar/index")['Calendar']
    'UiCalendarCell': typeof import("../../components/ui/calendar/index")['CalendarCell']
    'UiCalendarCellTrigger': typeof import("../../components/ui/calendar/index")['CalendarCellTrigger']
    'UiCalendarGrid': typeof import("../../components/ui/calendar/index")['CalendarGrid']
    'UiCalendarGridBody': typeof import("../../components/ui/calendar/index")['CalendarGridBody']
    'UiCalendarGridHead': typeof import("../../components/ui/calendar/index")['CalendarGridHead']
    'UiCalendarGridRow': typeof import("../../components/ui/calendar/index")['CalendarGridRow']
    'UiCalendarHeadCell': typeof import("../../components/ui/calendar/index")['CalendarHeadCell']
    'UiCalendarHeader': typeof import("../../components/ui/calendar/index")['CalendarHeader']
    'UiCalendarHeading': typeof import("../../components/ui/calendar/index")['CalendarHeading']
    'UiCalendarNextButton': typeof import("../../components/ui/calendar/index")['CalendarNextButton']
    'UiCalendarPrevButton': typeof import("../../components/ui/calendar/index")['CalendarPrevButton']
    'UiCard': typeof import("../../components/ui/card/index")['Card']
    'UiCardAction': typeof import("../../components/ui/card/index")['CardAction']
    'UiCardContent': typeof import("../../components/ui/card/index")['CardContent']
    'UiCardDescription': typeof import("../../components/ui/card/index")['CardDescription']
    'UiCardFooter': typeof import("../../components/ui/card/index")['CardFooter']
    'UiCardHeader': typeof import("../../components/ui/card/index")['CardHeader']
    'UiCardTitle': typeof import("../../components/ui/card/index")['CardTitle']
    'UiCheckbox': typeof import("../../components/ui/checkbox/index")['Checkbox']
    'UiCombobox': typeof import("../../components/ui/combobox/index")['Combobox']
    'UiComboboxAnchor': typeof import("../../components/ui/combobox/index")['ComboboxAnchor']
    'UiComboboxEmpty': typeof import("../../components/ui/combobox/index")['ComboboxEmpty']
    'UiComboboxGroup': typeof import("../../components/ui/combobox/index")['ComboboxGroup']
    'UiComboboxInput': typeof import("../../components/ui/combobox/index")['ComboboxInput']
    'UiComboboxItem': typeof import("../../components/ui/combobox/index")['ComboboxItem']
    'UiComboboxItemIndicator': typeof import("../../components/ui/combobox/index")['ComboboxItemIndicator']
    'UiComboboxList': typeof import("../../components/ui/combobox/index")['ComboboxList']
    'UiComboboxSeparator': typeof import("../../components/ui/combobox/index")['ComboboxSeparator']
    'UiComboboxTrigger': typeof import("../../components/ui/combobox/index")['ComboboxTrigger']
    'UiComboboxViewport': typeof import("../../components/ui/combobox/index")['ComboboxViewport']
    'UiComboboxCancel': typeof import("../../components/ui/combobox/index")['ComboboxCancel']
    'UiCommand': typeof import("../../components/ui/command/index")['Command']
    'UiCommandDialog': typeof import("../../components/ui/command/index")['CommandDialog']
    'UiCommandEmpty': typeof import("../../components/ui/command/index")['CommandEmpty']
    'UiCommandGroup': typeof import("../../components/ui/command/index")['CommandGroup']
    'UiCommandInput': typeof import("../../components/ui/command/index")['CommandInput']
    'UiCommandItem': typeof import("../../components/ui/command/index")['CommandItem']
    'UiCommandList': typeof import("../../components/ui/command/index")['CommandList']
    'UiCommandSeparator': typeof import("../../components/ui/command/index")['CommandSeparator']
    'UiCommandShortcut': typeof import("../../components/ui/command/index")['CommandShortcut']
    'UiDialog': typeof import("../../components/ui/dialog/index")['Dialog']
    'UiDialogClose': typeof import("../../components/ui/dialog/index")['DialogClose']
    'UiDialogContent': typeof import("../../components/ui/dialog/index")['DialogContent']
    'UiDialogDescription': typeof import("../../components/ui/dialog/index")['DialogDescription']
    'UiDialogFooter': typeof import("../../components/ui/dialog/index")['DialogFooter']
    'UiDialogHeader': typeof import("../../components/ui/dialog/index")['DialogHeader']
    'UiDialogOverlay': typeof import("../../components/ui/dialog/index")['DialogOverlay']
    'UiDialogScrollContent': typeof import("../../components/ui/dialog/index")['DialogScrollContent']
    'UiDialogTitle': typeof import("../../components/ui/dialog/index")['DialogTitle']
    'UiDialogTrigger': typeof import("../../components/ui/dialog/index")['DialogTrigger']
    'UiDropdownMenu': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenu']
    'UiDropdownMenuCheckboxItem': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'UiDropdownMenuContent': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'UiDropdownMenuGroup': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'UiDropdownMenuItem': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'UiDropdownMenuLabel': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'UiDropdownMenuRadioGroup': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'UiDropdownMenuRadioItem': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'UiDropdownMenuSeparator': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'UiDropdownMenuShortcut': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'UiDropdownMenuSub': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'UiDropdownMenuSubContent': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'UiDropdownMenuSubTrigger': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'UiDropdownMenuTrigger': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'UiDropdownMenuPortal': typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'UiFormControl': typeof import("../../components/ui/form/index")['FormControl']
    'UiFormDescription': typeof import("../../components/ui/form/index")['FormDescription']
    'UiFormItem': typeof import("../../components/ui/form/index")['FormItem']
    'UiFormLabel': typeof import("../../components/ui/form/index")['FormLabel']
    'UiFormMessage': typeof import("../../components/ui/form/index")['FormMessage']
    'UiFORMITEMINJECTIONKEY': typeof import("../../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
    'UiForm': typeof import("../../components/ui/form/index")['Form']
    'UiFormField': typeof import("../../components/ui/form/index")['FormField']
    'UiFormFieldArray': typeof import("../../components/ui/form/index")['FormFieldArray']
    'UiInput': typeof import("../../components/ui/input/index")['Input']
    'UiLabel': typeof import("../../components/ui/label/index")['Label']
    'UiPopover': typeof import("../../components/ui/popover/index")['Popover']
    'UiPopoverAnchor': typeof import("../../components/ui/popover/index")['PopoverAnchor']
    'UiPopoverContent': typeof import("../../components/ui/popover/index")['PopoverContent']
    'UiPopoverTrigger': typeof import("../../components/ui/popover/index")['PopoverTrigger']
    'UiSelect': typeof import("../../components/ui/select/index")['Select']
    'UiSelectContent': typeof import("../../components/ui/select/index")['SelectContent']
    'UiSelectGroup': typeof import("../../components/ui/select/index")['SelectGroup']
    'UiSelectItem': typeof import("../../components/ui/select/index")['SelectItem']
    'UiSelectItemText': typeof import("../../components/ui/select/index")['SelectItemText']
    'UiSelectLabel': typeof import("../../components/ui/select/index")['SelectLabel']
    'UiSelectScrollDownButton': typeof import("../../components/ui/select/index")['SelectScrollDownButton']
    'UiSelectScrollUpButton': typeof import("../../components/ui/select/index")['SelectScrollUpButton']
    'UiSelectSeparator': typeof import("../../components/ui/select/index")['SelectSeparator']
    'UiSelectTrigger': typeof import("../../components/ui/select/index")['SelectTrigger']
    'UiSelectValue': typeof import("../../components/ui/select/index")['SelectValue']
    'UiSkeleton': typeof import("../../components/ui/skeleton/index")['Skeleton']
    'UiToaster': typeof import("../../components/ui/sonner/index")['Toaster']
    'UiTable': typeof import("../../components/ui/table/index")['Table']
    'UiTableBody': typeof import("../../components/ui/table/index")['TableBody']
    'UiTableCaption': typeof import("../../components/ui/table/index")['TableCaption']
    'UiTableCell': typeof import("../../components/ui/table/index")['TableCell']
    'UiTableEmpty': typeof import("../../components/ui/table/index")['TableEmpty']
    'UiTableFooter': typeof import("../../components/ui/table/index")['TableFooter']
    'UiTableHead': typeof import("../../components/ui/table/index")['TableHead']
    'UiTableHeader': typeof import("../../components/ui/table/index")['TableHeader']
    'UiTableRow': typeof import("../../components/ui/table/index")['TableRow']
    'UiTabs': typeof import("../../components/ui/tabs/index")['Tabs']
    'UiTabsContent': typeof import("../../components/ui/tabs/index")['TabsContent']
    'UiTabsList': typeof import("../../components/ui/tabs/index")['TabsList']
    'UiTabsTrigger': typeof import("../../components/ui/tabs/index")['TabsTrigger']
    'UiTextarea': typeof import("../../components/ui/textarea/index")['Textarea']
    'UiTooltip': typeof import("../../components/ui/tooltip/index")['Tooltip']
    'UiTooltipContent': typeof import("../../components/ui/tooltip/index")['TooltipContent']
    'UiTooltipProvider': typeof import("../../components/ui/tooltip/index")['TooltipProvider']
    'UiTooltipTrigger': typeof import("../../components/ui/tooltip/index")['TooltipTrigger']
    'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'AppICDBrowser': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
      'LazyBreadcrumb': LazyComponent<typeof import("../../components/ui/breadcrumb/Breadcrumb.vue")['default']>
    'LazyBreadcrumbEllipsis': LazyComponent<typeof import("../../components/ui/breadcrumb/BreadcrumbEllipsis.vue")['default']>
    'LazyBreadcrumbItem': LazyComponent<typeof import("../../components/ui/breadcrumb/BreadcrumbItem.vue")['default']>
    'LazyBreadcrumbLink': LazyComponent<typeof import("../../components/ui/breadcrumb/BreadcrumbLink.vue")['default']>
    'LazyBreadcrumbList': LazyComponent<typeof import("../../components/ui/breadcrumb/BreadcrumbList.vue")['default']>
    'LazyBreadcrumbPage': LazyComponent<typeof import("../../components/ui/breadcrumb/BreadcrumbPage.vue")['default']>
    'LazyBreadcrumbSeparator': LazyComponent<typeof import("../../components/ui/breadcrumb/BreadcrumbSeparator.vue")['default']>
    'LazyButton': LazyComponent<typeof import("../../components/ui/button/Button.vue")['default']>
    'LazyCalendar': LazyComponent<typeof import("../../components/ui/calendar/Calendar.vue")['default']>
    'LazyCalendarCell': LazyComponent<typeof import("../../components/ui/calendar/CalendarCell.vue")['default']>
    'LazyCalendarCellTrigger': LazyComponent<typeof import("../../components/ui/calendar/CalendarCellTrigger.vue")['default']>
    'LazyCalendarGrid': LazyComponent<typeof import("../../components/ui/calendar/CalendarGrid.vue")['default']>
    'LazyCalendarGridBody': LazyComponent<typeof import("../../components/ui/calendar/CalendarGridBody.vue")['default']>
    'LazyCalendarGridHead': LazyComponent<typeof import("../../components/ui/calendar/CalendarGridHead.vue")['default']>
    'LazyCalendarGridRow': LazyComponent<typeof import("../../components/ui/calendar/CalendarGridRow.vue")['default']>
    'LazyCalendarHeadCell': LazyComponent<typeof import("../../components/ui/calendar/CalendarHeadCell.vue")['default']>
    'LazyCalendarHeader': LazyComponent<typeof import("../../components/ui/calendar/CalendarHeader.vue")['default']>
    'LazyCalendarHeading': LazyComponent<typeof import("../../components/ui/calendar/CalendarHeading.vue")['default']>
    'LazyCalendarNextButton': LazyComponent<typeof import("../../components/ui/calendar/CalendarNextButton.vue")['default']>
    'LazyCalendarPrevButton': LazyComponent<typeof import("../../components/ui/calendar/CalendarPrevButton.vue")['default']>
    'LazyCard': LazyComponent<typeof import("../../components/ui/card/Card.vue")['default']>
    'LazyCardAction': LazyComponent<typeof import("../../components/ui/card/CardAction.vue")['default']>
    'LazyCardContent': LazyComponent<typeof import("../../components/ui/card/CardContent.vue")['default']>
    'LazyCardDescription': LazyComponent<typeof import("../../components/ui/card/CardDescription.vue")['default']>
    'LazyCardFooter': LazyComponent<typeof import("../../components/ui/card/CardFooter.vue")['default']>
    'LazyCardHeader': LazyComponent<typeof import("../../components/ui/card/CardHeader.vue")['default']>
    'LazyCardTitle': LazyComponent<typeof import("../../components/ui/card/CardTitle.vue")['default']>
    'LazyCheckbox': LazyComponent<typeof import("../../components/ui/checkbox/Checkbox.vue")['default']>
    'LazyCombobox': LazyComponent<typeof import("../../components/ui/combobox/Combobox.vue")['default']>
    'LazyComboboxAnchor': LazyComponent<typeof import("../../components/ui/combobox/ComboboxAnchor.vue")['default']>
    'LazyComboboxEmpty': LazyComponent<typeof import("../../components/ui/combobox/ComboboxEmpty.vue")['default']>
    'LazyComboboxGroup': LazyComponent<typeof import("../../components/ui/combobox/ComboboxGroup.vue")['default']>
    'LazyComboboxInput': LazyComponent<typeof import("../../components/ui/combobox/ComboboxInput.vue")['default']>
    'LazyComboboxItem': LazyComponent<typeof import("../../components/ui/combobox/ComboboxItem.vue")['default']>
    'LazyComboboxItemIndicator': LazyComponent<typeof import("../../components/ui/combobox/ComboboxItemIndicator.vue")['default']>
    'LazyComboboxList': LazyComponent<typeof import("../../components/ui/combobox/ComboboxList.vue")['default']>
    'LazyComboboxSeparator': LazyComponent<typeof import("../../components/ui/combobox/ComboboxSeparator.vue")['default']>
    'LazyComboboxTrigger': LazyComponent<typeof import("../../components/ui/combobox/ComboboxTrigger.vue")['default']>
    'LazyComboboxViewport': LazyComponent<typeof import("../../components/ui/combobox/ComboboxViewport.vue")['default']>
    'LazyCommand': LazyComponent<typeof import("../../components/ui/command/Command.vue")['default']>
    'LazyCommandDialog': LazyComponent<typeof import("../../components/ui/command/CommandDialog.vue")['default']>
    'LazyCommandEmpty': LazyComponent<typeof import("../../components/ui/command/CommandEmpty.vue")['default']>
    'LazyCommandGroup': LazyComponent<typeof import("../../components/ui/command/CommandGroup.vue")['default']>
    'LazyCommandInput': LazyComponent<typeof import("../../components/ui/command/CommandInput.vue")['default']>
    'LazyCommandItem': LazyComponent<typeof import("../../components/ui/command/CommandItem.vue")['default']>
    'LazyCommandList': LazyComponent<typeof import("../../components/ui/command/CommandList.vue")['default']>
    'LazyCommandSeparator': LazyComponent<typeof import("../../components/ui/command/CommandSeparator.vue")['default']>
    'LazyCommandShortcut': LazyComponent<typeof import("../../components/ui/command/CommandShortcut.vue")['default']>
    'LazyDialog': LazyComponent<typeof import("../../components/ui/dialog/Dialog.vue")['default']>
    'LazyDialogClose': LazyComponent<typeof import("../../components/ui/dialog/DialogClose.vue")['default']>
    'LazyDialogContent': LazyComponent<typeof import("../../components/ui/dialog/DialogContent.vue")['default']>
    'LazyDialogDescription': LazyComponent<typeof import("../../components/ui/dialog/DialogDescription.vue")['default']>
    'LazyDialogFooter': LazyComponent<typeof import("../../components/ui/dialog/DialogFooter.vue")['default']>
    'LazyDialogHeader': LazyComponent<typeof import("../../components/ui/dialog/DialogHeader.vue")['default']>
    'LazyDialogOverlay': LazyComponent<typeof import("../../components/ui/dialog/DialogOverlay.vue")['default']>
    'LazyDialogScrollContent': LazyComponent<typeof import("../../components/ui/dialog/DialogScrollContent.vue")['default']>
    'LazyDialogTitle': LazyComponent<typeof import("../../components/ui/dialog/DialogTitle.vue")['default']>
    'LazyDialogTrigger': LazyComponent<typeof import("../../components/ui/dialog/DialogTrigger.vue")['default']>
    'LazyDropdownMenu': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenu.vue")['default']>
    'LazyDropdownMenuCheckboxItem': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']>
    'LazyDropdownMenuContent': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuContent.vue")['default']>
    'LazyDropdownMenuGroup': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']>
    'LazyDropdownMenuItem': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuItem.vue")['default']>
    'LazyDropdownMenuLabel': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']>
    'LazyDropdownMenuRadioGroup': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']>
    'LazyDropdownMenuRadioItem': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']>
    'LazyDropdownMenuSeparator': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']>
    'LazyDropdownMenuShortcut': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']>
    'LazyDropdownMenuSub': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuSub.vue")['default']>
    'LazyDropdownMenuSubContent': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']>
    'LazyDropdownMenuSubTrigger': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']>
    'LazyDropdownMenuTrigger': LazyComponent<typeof import("../../components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']>
    'LazyFormControl': LazyComponent<typeof import("../../components/ui/form/FormControl.vue")['default']>
    'LazyFormDescription': LazyComponent<typeof import("../../components/ui/form/FormDescription.vue")['default']>
    'LazyFormItem': LazyComponent<typeof import("../../components/ui/form/FormItem.vue")['default']>
    'LazyFormLabel': LazyComponent<typeof import("../../components/ui/form/FormLabel.vue")['default']>
    'LazyFormMessage': LazyComponent<typeof import("../../components/ui/form/FormMessage.vue")['default']>
    'LazyForm': LazyComponent<typeof import("../../components/ui/form/index")['default']>
    'LazyFormInjectionKeys': LazyComponent<typeof import("../../components/ui/form/injectionKeys")['default']>
    'LazyFormUseFormField': LazyComponent<typeof import("../../components/ui/form/useFormField")['default']>
    'LazyInput': LazyComponent<typeof import("../../components/ui/input/Input.vue")['default']>
    'LazyLabel': LazyComponent<typeof import("../../components/ui/label/Label.vue")['default']>
    'LazyPopover': LazyComponent<typeof import("../../components/ui/popover/Popover.vue")['default']>
    'LazyPopoverAnchor': LazyComponent<typeof import("../../components/ui/popover/PopoverAnchor.vue")['default']>
    'LazyPopoverContent': LazyComponent<typeof import("../../components/ui/popover/PopoverContent.vue")['default']>
    'LazyPopoverTrigger': LazyComponent<typeof import("../../components/ui/popover/PopoverTrigger.vue")['default']>
    'LazySelect': LazyComponent<typeof import("../../components/ui/select/Select.vue")['default']>
    'LazySelectContent': LazyComponent<typeof import("../../components/ui/select/SelectContent.vue")['default']>
    'LazySelectGroup': LazyComponent<typeof import("../../components/ui/select/SelectGroup.vue")['default']>
    'LazySelectItem': LazyComponent<typeof import("../../components/ui/select/SelectItem.vue")['default']>
    'LazySelectItemText': LazyComponent<typeof import("../../components/ui/select/SelectItemText.vue")['default']>
    'LazySelectLabel': LazyComponent<typeof import("../../components/ui/select/SelectLabel.vue")['default']>
    'LazySelectScrollDownButton': LazyComponent<typeof import("../../components/ui/select/SelectScrollDownButton.vue")['default']>
    'LazySelectScrollUpButton': LazyComponent<typeof import("../../components/ui/select/SelectScrollUpButton.vue")['default']>
    'LazySelectSeparator': LazyComponent<typeof import("../../components/ui/select/SelectSeparator.vue")['default']>
    'LazySelectTrigger': LazyComponent<typeof import("../../components/ui/select/SelectTrigger.vue")['default']>
    'LazySelectValue': LazyComponent<typeof import("../../components/ui/select/SelectValue.vue")['default']>
    'LazySkeleton': LazyComponent<typeof import("../../components/ui/skeleton/Skeleton.vue")['default']>
    'LazySonner': LazyComponent<typeof import("../../components/ui/sonner/Sonner.vue")['default']>
    'LazyTable': LazyComponent<typeof import("../../components/ui/table/Table.vue")['default']>
    'LazyTableBody': LazyComponent<typeof import("../../components/ui/table/TableBody.vue")['default']>
    'LazyTableCaption': LazyComponent<typeof import("../../components/ui/table/TableCaption.vue")['default']>
    'LazyTableCell': LazyComponent<typeof import("../../components/ui/table/TableCell.vue")['default']>
    'LazyTableEmpty': LazyComponent<typeof import("../../components/ui/table/TableEmpty.vue")['default']>
    'LazyTableFooter': LazyComponent<typeof import("../../components/ui/table/TableFooter.vue")['default']>
    'LazyTableHead': LazyComponent<typeof import("../../components/ui/table/TableHead.vue")['default']>
    'LazyTableHeader': LazyComponent<typeof import("../../components/ui/table/TableHeader.vue")['default']>
    'LazyTableRow': LazyComponent<typeof import("../../components/ui/table/TableRow.vue")['default']>
    'LazyTableUtils': LazyComponent<typeof import("../../components/ui/table/utils")['default']>
    'LazyTabs': LazyComponent<typeof import("../../components/ui/tabs/Tabs.vue")['default']>
    'LazyTabsContent': LazyComponent<typeof import("../../components/ui/tabs/TabsContent.vue")['default']>
    'LazyTabsList': LazyComponent<typeof import("../../components/ui/tabs/TabsList.vue")['default']>
    'LazyTabsTrigger': LazyComponent<typeof import("../../components/ui/tabs/TabsTrigger.vue")['default']>
    'LazyTextarea': LazyComponent<typeof import("../../components/ui/textarea/Textarea.vue")['default']>
    'LazyTooltip': LazyComponent<typeof import("../../components/ui/tooltip/Tooltip.vue")['default']>
    'LazyTooltipContent': LazyComponent<typeof import("../../components/ui/tooltip/TooltipContent.vue")['default']>
    'LazyTooltipProvider': LazyComponent<typeof import("../../components/ui/tooltip/TooltipProvider.vue")['default']>
    'LazyTooltipTrigger': LazyComponent<typeof import("../../components/ui/tooltip/TooltipTrigger.vue")['default']>
    'LazyAdminDashboardAdminStatsCards': LazyComponent<typeof import("../../components/admin/dashboard/AdminStatsCards.vue")['default']>
    'LazyAdminDashboardAdminWelcomeHeader': LazyComponent<typeof import("../../components/admin/dashboard/AdminWelcomeHeader.vue")['default']>
    'LazyAdminDashboardAnalyticsChart': LazyComponent<typeof import("../../components/admin/dashboard/AnalyticsChart.vue")['default']>
    'LazyAdminDashboardSystemMetrics': LazyComponent<typeof import("../../components/admin/dashboard/SystemMetrics.vue")['default']>
    'LazyAdminDashboardUserManagement': LazyComponent<typeof import("../../components/admin/dashboard/UserManagement.vue")['default']>
    'LazyAppFormTypedCheckbox': LazyComponent<typeof import("../../components/app/form/TypedCheckbox.vue")['default']>
    'LazyAppFormTypedCombobox': LazyComponent<typeof import("../../components/app/form/TypedCombobox.vue")['default']>
    'LazyAppFormTypedDate': LazyComponent<typeof import("../../components/app/form/TypedDate.vue")['default']>
    'LazyAppFormTypedDatetime': LazyComponent<typeof import("../../components/app/form/TypedDatetime.vue")['default']>
    'LazyAppFormTypedFile': LazyComponent<typeof import("../../components/app/form/TypedFile.vue")['default']>
    'LazyAppFormTypedForm': LazyComponent<typeof import("../../components/app/form/TypedForm.vue")['default']>
    'LazyAppFormTypedInput': LazyComponent<typeof import("../../components/app/form/TypedInput.vue")['default']>
    'LazyAppFormTypedNumber': LazyComponent<typeof import("../../components/app/form/TypedNumber.vue")['default']>
    'LazyAppFormTypedSelect': LazyComponent<typeof import("../../components/app/form/TypedSelect.vue")['default']>
    'LazyAppFormTypedTextarea': LazyComponent<typeof import("../../components/app/form/TypedTextarea.vue")['default']>
    'LazyAppFormTypedTime': LazyComponent<typeof import("../../components/app/form/TypedTime.vue")['default']>
    'LazyAppForm': LazyComponent<typeof import("../../components/app/form/index")['default']>
    'LazyAppICDBrowser': LazyComponent<typeof import("../../components/app/icd/ICDBrowser.client.vue")['default']>
    'LazyAppIcd': LazyComponent<typeof import("../../components/app/icd/index")['default']>
    'LazyAppOCRCanvas': LazyComponent<typeof import("../../components/app/ocr/OCRCanvas.vue")['default']>
    'LazyAppOCRDialog': LazyComponent<typeof import("../../components/app/ocr/OCRDialog.vue")['default']>
    'LazyAppOcr': LazyComponent<typeof import("../../components/app/ocr/index")['default']>
    'LazyAppQrcodeQRCodeDisplay': LazyComponent<typeof import("../../components/app/qrcode/QRCodeDisplay.vue")['default']>
    'LazyAppQrcodeQRCodeScanner': LazyComponent<typeof import("../../components/app/qrcode/QRCodeScanner.vue")['default']>
    'LazyAppQrcode': LazyComponent<typeof import("../../components/app/qrcode/index")['default']>
    'LazyAppReportsLineChartTile': LazyComponent<typeof import("../../components/app/reports/LineChartTile.vue")['default']>
    'LazyAppReportsNumericTile': LazyComponent<typeof import("../../components/app/reports/NumericTile.vue")['default']>
    'LazyAppReportsPieChartTile': LazyComponent<typeof import("../../components/app/reports/PieChartTile.vue")['default']>
    'LazyAppReports': LazyComponent<typeof import("../../components/app/reports/index")['default']>
    'LazyLayoutBreadcrumbsPageBreadcrumbs': LazyComponent<typeof import("../../components/layout/breadcrumbs/PageBreadcrumbs.vue")['default']>
    'LazyLayoutBreadcrumbs': LazyComponent<typeof import("../../components/layout/breadcrumbs/index")['default']>
    'LazyLayoutCommandDialog': LazyComponent<typeof import("../../components/layout/command/CommandDialog.vue")['default']>
    'LazyLayoutCommandGroup': LazyComponent<typeof import("../../components/layout/command/CommandGroup.vue")['default']>
    'LazyLayoutCommandPalette': LazyComponent<typeof import("../../components/layout/command/CommandPalette.vue")['default']>
    'LazyLayoutCommand': LazyComponent<typeof import("../../components/layout/command/index")['default']>
    'LazyLayoutNotificationsPopover': LazyComponent<typeof import("../../components/layout/notifications/NotificationsPopover.vue")['default']>
    'LazyLayoutNotifications': LazyComponent<typeof import("../../components/layout/notifications/index")['default']>
    'LazyLayoutSidebarBase': LazyComponent<typeof import("../../components/layout/sidebar/SidebarBase.vue")['default']>
    'LazyLayoutSidebarFooter': LazyComponent<typeof import("../../components/layout/sidebar/SidebarFooter.vue")['default']>
    'LazyLayoutSidebarGroup': LazyComponent<typeof import("../../components/layout/sidebar/SidebarGroup.vue")['default']>
    'LazyLayoutSidebarHeader': LazyComponent<typeof import("../../components/layout/sidebar/SidebarHeader.vue")['default']>
    'LazyLayoutSidebarItem': LazyComponent<typeof import("../../components/layout/sidebar/SidebarItem.vue")['default']>
    'LazyLayoutSidebar': LazyComponent<typeof import("../../components/layout/sidebar/index")['default']>
    'LazyStaffDashboardAnalyticsChart': LazyComponent<typeof import("../../components/staff/dashboard/AnalyticsChart.vue")['default']>
    'LazyStaffDashboardRecentActivities': LazyComponent<typeof import("../../components/staff/dashboard/RecentActivities.vue")['default']>
    'LazyStaffDashboardStatsCards': LazyComponent<typeof import("../../components/staff/dashboard/StatsCards.vue")['default']>
    'LazyStaffDashboardTodaysAppointments': LazyComponent<typeof import("../../components/staff/dashboard/TodaysAppointments.vue")['default']>
    'LazyStaffDashboardWelcomeHeader': LazyComponent<typeof import("../../components/staff/dashboard/WelcomeHeader.vue")['default']>
    'LazyAboutUsForm': LazyComponent<typeof import("../../pages/(public)/platform/components/AboutUsForm.vue")['default']>
    'LazyEnterpriseForm': LazyComponent<typeof import("../../pages/(public)/platform/components/EnterpriseForm.vue")['default']>
    'LazyLoginForm': LazyComponent<typeof import("../../pages/(public)/platform/components/LoginForm.vue")['default']>
    'LazyPrivacyPolicyForm': LazyComponent<typeof import("../../pages/(public)/platform/components/PrivacyPolicyForm.vue")['default']>
    'LazyProfessionalForm': LazyComponent<typeof import("../../pages/(public)/platform/components/ProfessionalForm.vue")['default']>
    'LazyServicesForm': LazyComponent<typeof import("../../pages/(public)/platform/components/ServicesForm.vue")['default']>
    'LazySignUpForm': LazyComponent<typeof import("../../pages/(public)/platform/components/SignUpForm.vue")['default']>
    'LazyStartUpForm': LazyComponent<typeof import("../../pages/(public)/platform/components/StartUpForm.vue")['default']>
    'LazySupportForm': LazyComponent<typeof import("../../pages/(public)/platform/components/SupportForm.vue")['default']>
    'LazyTermsOfUseForm': LazyComponent<typeof import("../../pages/(public)/platform/components/TermsOfUseForm.vue")['default']>
    'LazyLogEntityCell': LazyComponent<typeof import("../../pages/admin/logs/components/LogEntityCell.vue")['default']>
    'LazyLogsTable': LazyComponent<typeof import("../../pages/admin/logs/components/LogsTable.vue")['default']>
    'LazyUserProfileForm': LazyComponent<typeof import("../../pages/admin/users/components/UserProfileForm.vue")['default']>
    'LazyIndexDashboard': LazyComponent<typeof import("../../pages/index/components/IndexDashboard.vue")['default']>
    'LazyClaimRequestForm': LazyComponent<typeof import("../../pages/partner/components/ClaimRequestForm.vue")['default']>
    'LazyClaimRequestsTable': LazyComponent<typeof import("../../pages/partner/components/ClaimRequestsTable.vue")['default']>
    'LazyDataRequestForm': LazyComponent<typeof import("../../pages/partner/components/DataRequestForm.vue")['default']>
    'LazyDataRequestsTable': LazyComponent<typeof import("../../pages/partner/components/DataRequestsTable.vue")['default']>
    'LazyPartnerForm': LazyComponent<typeof import("../../pages/partner/components/PartnerForm.vue")['default']>
    'LazyPartnerTable': LazyComponent<typeof import("../../pages/partner/components/PartnerTable.vue")['default']>
    'LazyPatientAppointmentFilters': LazyComponent<typeof import("../../pages/patient/appointments/components/PatientAppointmentFilters.vue")['default']>
    'LazyPatientAppointmentForm': LazyComponent<typeof import("../../pages/patient/appointments/components/PatientAppointmentForm.vue")['default']>
    'LazyPatientAppointmentsAvailability': LazyComponent<typeof import("../../pages/patient/appointments/components/PatientAppointmentsAvailability.vue")['default']>
    'LazyPatientAppointmentsTable': LazyComponent<typeof import("../../pages/patient/appointments/components/PatientAppointmentsTable.vue")['default']>
    'LazyPatientsBillingTable': LazyComponent<typeof import("../../pages/patient/billing/components/PatientsBillingTable.vue")['default']>
    'LazyDoctorTable': LazyComponent<typeof import("../../pages/patient/doctor/components/DoctorTable.vue")['default']>
    'LazyMedicalRecordForm': LazyComponent<typeof import("../../pages/patient/medical-records/components/MedicalRecordForm.vue")['default']>
    'LazyMedicalRecordsTable': LazyComponent<typeof import("../../pages/patient/medical-records/components/MedicalRecordsTable.vue")['default']>
    'LazyAppointmentFilters': LazyComponent<typeof import("../../pages/staff/appointments/components/AppointmentFilters.vue")['default']>
    'LazyAppointmentForm': LazyComponent<typeof import("../../pages/staff/appointments/components/AppointmentForm.vue")['default']>
    'LazyAppointmentsAvailability': LazyComponent<typeof import("../../pages/staff/appointments/components/AppointmentsAvailability.vue")['default']>
    'LazyAppointmentsTable': LazyComponent<typeof import("../../pages/staff/appointments/components/AppointmentsTable.vue")['default']>
    'LazyBillingPaymentForm': LazyComponent<typeof import("../../pages/staff/billing/components/BillingPaymentForm.vue")['default']>
    'LazyBillingPaymentInstalmentForm': LazyComponent<typeof import("../../pages/staff/billing/components/BillingPaymentInstalmentForm.vue")['default']>
    'LazyBillingPaymentInstalmentTable': LazyComponent<typeof import("../../pages/staff/billing/components/BillingPaymentInstalmentTable.vue")['default']>
    'LazyBillingPaymentPlanForm': LazyComponent<typeof import("../../pages/staff/billing/components/BillingPaymentPlanForm.vue")['default']>
    'LazyBillingPaymentPlansTable': LazyComponent<typeof import("../../pages/staff/billing/components/BillingPaymentPlansTable.vue")['default']>
    'LazyBillingPaymentsTable': LazyComponent<typeof import("../../pages/staff/billing/components/BillingPaymentsTable.vue")['default']>
    'LazyBillingTransactionForm': LazyComponent<typeof import("../../pages/staff/billing/components/BillingTransactionForm.vue")['default']>
    'LazyBillingTransactionItemForm': LazyComponent<typeof import("../../pages/staff/billing/components/BillingTransactionItemForm.vue")['default']>
    'LazyBillingTransactionItemsTable': LazyComponent<typeof import("../../pages/staff/billing/components/BillingTransactionItemsTable.vue")['default']>
    'LazyBillingTransactionsTable': LazyComponent<typeof import("../../pages/staff/billing/components/BillingTransactionsTable.vue")['default']>
    'LazyAppointmentsList': LazyComponent<typeof import("../../pages/staff/dashboard/components/AppointmentsList.vue")['default']>
    'LazyDashboardFilters': LazyComponent<typeof import("../../pages/staff/dashboard/components/DashboardFilters.vue")['default']>
    'LazyDashboardSummaryCards': LazyComponent<typeof import("../../pages/staff/dashboard/components/DashboardSummaryCards.vue")['default']>
    'LazyDoctorDashboard': LazyComponent<typeof import("../../pages/staff/dashboard/components/DoctorDashboard.vue")['default']>
    'LazySecretaryDashboard': LazyComponent<typeof import("../../pages/staff/dashboard/components/SecretaryDashboard.vue")['default']>
    'LazyBuildingForm': LazyComponent<typeof import("../../pages/staff/facilities/components/BuildingForm.vue")['default']>
    'LazyBuildingsTable': LazyComponent<typeof import("../../pages/staff/facilities/components/BuildingsTable.vue")['default']>
    'LazyFacilitiesTable': LazyComponent<typeof import("../../pages/staff/facilities/components/FacilitiesTable.vue")['default']>
    'LazyFacilityForm': LazyComponent<typeof import("../../pages/staff/facilities/components/FacilityForm.vue")['default']>
    'LazyFacilityLogsTable': LazyComponent<typeof import("../../pages/staff/facilities/components/FacilityLogsTable.vue")['default']>
    'LazyInsuranceClaimForm': LazyComponent<typeof import("../../pages/staff/insurance/components/InsuranceClaimForm.vue")['default']>
    'LazyInsuranceClaimItemForm': LazyComponent<typeof import("../../pages/staff/insurance/components/InsuranceClaimItemForm.vue")['default']>
    'LazyInsuranceClaimItemsTable': LazyComponent<typeof import("../../pages/staff/insurance/components/InsuranceClaimItemsTable.vue")['default']>
    'LazyInsuranceClaimsTable': LazyComponent<typeof import("../../pages/staff/insurance/components/InsuranceClaimsTable.vue")['default']>
    'LazyInsuranceProviderForm': LazyComponent<typeof import("../../pages/staff/insurance/components/InsuranceProviderForm.vue")['default']>
    'LazyInsuranceProviderTable': LazyComponent<typeof import("../../pages/staff/insurance/components/InsuranceProviderTable.vue")['default']>
    'LazyEncountersModule': LazyComponent<typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/EncountersModule.vue")['default']>
    'LazyInpatientForm': LazyComponent<typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/InpatientForm.vue")['default']>
    'LazyOutpatientForm': LazyComponent<typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/OutpatientForm.vue")['default']>
    'LazyEncountersTable': LazyComponent<typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/components/EncountersTable.vue")['default']>
    'LazyInpatientTable': LazyComponent<typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/components/InpatientTable.vue")['default']>
    'LazyOutpatientTable': LazyComponent<typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/components/OutpatientTable.vue")['default']>
    'Lazy[inpatientEncounterId]': LazyComponent<typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/inpatient/[inpatientEncounterId].vue")['default']>
    'Lazy[outpatientEncounterId]': LazyComponent<typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/outpatient/[outpatientEncounterId].vue")['default']>
    'LazyNew': LazyComponent<typeof import("../../pages/staff/patients/[patientProfileId]/encounters/components/outpatient/new.vue")['default']>
    'LazyAddressFields': LazyComponent<typeof import("../../pages/staff/patients/components/AddressFields.vue")['default']>
    'LazyConsentFields': LazyComponent<typeof import("../../pages/staff/patients/components/ConsentFields.vue")['default']>
    'LazyContactFields': LazyComponent<typeof import("../../pages/staff/patients/components/ContactFields.vue")['default']>
    'LazyEmergencyContactFields': LazyComponent<typeof import("../../pages/staff/patients/components/EmergencyContactFields.vue")['default']>
    'LazyEmploymentFields': LazyComponent<typeof import("../../pages/staff/patients/components/EmploymentFields.vue")['default']>
    'LazyPatientProfileForm': LazyComponent<typeof import("../../pages/staff/patients/components/PatientProfileForm.vue")['default']>
    'LazyPatientProfileTable': LazyComponent<typeof import("../../pages/staff/patients/components/PatientProfileTable.vue")['default']>
    'LazyProfileFields': LazyComponent<typeof import("../../pages/staff/patients/components/ProfileFields.vue")['default']>
    'LazyPharmacyBrandForm': LazyComponent<typeof import("../../pages/staff/pharmacy/components/PharmacyBrandForm.vue")['default']>
    'LazyPharmacyBrandsTable': LazyComponent<typeof import("../../pages/staff/pharmacy/components/PharmacyBrandsTable.vue")['default']>
    'LazyPharmacyCategoriesTable': LazyComponent<typeof import("../../pages/staff/pharmacy/components/PharmacyCategoriesTable.vue")['default']>
    'LazyPharmacyCategoryForm': LazyComponent<typeof import("../../pages/staff/pharmacy/components/PharmacyCategoryForm.vue")['default']>
    'LazyPharmacyItemForm': LazyComponent<typeof import("../../pages/staff/pharmacy/components/PharmacyItemForm.vue")['default']>
    'LazyPharmacyItemsTable': LazyComponent<typeof import("../../pages/staff/pharmacy/components/PharmacyItemsTable.vue")['default']>
    'LazyPharmacySupplierForm': LazyComponent<typeof import("../../pages/staff/pharmacy/components/PharmacySupplierForm.vue")['default']>
    'LazyPharmacySuppliersTable': LazyComponent<typeof import("../../pages/staff/pharmacy/components/PharmacySuppliersTable.vue")['default']>
    'LazyStaffForm': LazyComponent<typeof import("../../pages/staff/staff/components/StaffForm.vue")['default']>
    'LazyStaffTable': LazyComponent<typeof import("../../pages/staff/staff/components/StaffTable.vue")['default']>
    'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
    'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
    'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
    'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
    'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
    'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
    'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
    'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
    'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
    'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
    'LazyIcon': LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
    'LazyUiBreadcrumb': LazyComponent<typeof import("../../components/ui/breadcrumb/index")['Breadcrumb']>
    'LazyUiBreadcrumbEllipsis': LazyComponent<typeof import("../../components/ui/breadcrumb/index")['BreadcrumbEllipsis']>
    'LazyUiBreadcrumbItem': LazyComponent<typeof import("../../components/ui/breadcrumb/index")['BreadcrumbItem']>
    'LazyUiBreadcrumbLink': LazyComponent<typeof import("../../components/ui/breadcrumb/index")['BreadcrumbLink']>
    'LazyUiBreadcrumbList': LazyComponent<typeof import("../../components/ui/breadcrumb/index")['BreadcrumbList']>
    'LazyUiBreadcrumbPage': LazyComponent<typeof import("../../components/ui/breadcrumb/index")['BreadcrumbPage']>
    'LazyUiBreadcrumbSeparator': LazyComponent<typeof import("../../components/ui/breadcrumb/index")['BreadcrumbSeparator']>
    'LazyUiButton': LazyComponent<typeof import("../../components/ui/button/index")['Button']>
    'LazyUiCalendar': LazyComponent<typeof import("../../components/ui/calendar/index")['Calendar']>
    'LazyUiCalendarCell': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarCell']>
    'LazyUiCalendarCellTrigger': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarCellTrigger']>
    'LazyUiCalendarGrid': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarGrid']>
    'LazyUiCalendarGridBody': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarGridBody']>
    'LazyUiCalendarGridHead': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarGridHead']>
    'LazyUiCalendarGridRow': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarGridRow']>
    'LazyUiCalendarHeadCell': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarHeadCell']>
    'LazyUiCalendarHeader': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarHeader']>
    'LazyUiCalendarHeading': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarHeading']>
    'LazyUiCalendarNextButton': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarNextButton']>
    'LazyUiCalendarPrevButton': LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarPrevButton']>
    'LazyUiCard': LazyComponent<typeof import("../../components/ui/card/index")['Card']>
    'LazyUiCardAction': LazyComponent<typeof import("../../components/ui/card/index")['CardAction']>
    'LazyUiCardContent': LazyComponent<typeof import("../../components/ui/card/index")['CardContent']>
    'LazyUiCardDescription': LazyComponent<typeof import("../../components/ui/card/index")['CardDescription']>
    'LazyUiCardFooter': LazyComponent<typeof import("../../components/ui/card/index")['CardFooter']>
    'LazyUiCardHeader': LazyComponent<typeof import("../../components/ui/card/index")['CardHeader']>
    'LazyUiCardTitle': LazyComponent<typeof import("../../components/ui/card/index")['CardTitle']>
    'LazyUiCheckbox': LazyComponent<typeof import("../../components/ui/checkbox/index")['Checkbox']>
    'LazyUiCombobox': LazyComponent<typeof import("../../components/ui/combobox/index")['Combobox']>
    'LazyUiComboboxAnchor': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxAnchor']>
    'LazyUiComboboxEmpty': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxEmpty']>
    'LazyUiComboboxGroup': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxGroup']>
    'LazyUiComboboxInput': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxInput']>
    'LazyUiComboboxItem': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxItem']>
    'LazyUiComboboxItemIndicator': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxItemIndicator']>
    'LazyUiComboboxList': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxList']>
    'LazyUiComboboxSeparator': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxSeparator']>
    'LazyUiComboboxTrigger': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxTrigger']>
    'LazyUiComboboxViewport': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxViewport']>
    'LazyUiComboboxCancel': LazyComponent<typeof import("../../components/ui/combobox/index")['ComboboxCancel']>
    'LazyUiCommand': LazyComponent<typeof import("../../components/ui/command/index")['Command']>
    'LazyUiCommandDialog': LazyComponent<typeof import("../../components/ui/command/index")['CommandDialog']>
    'LazyUiCommandEmpty': LazyComponent<typeof import("../../components/ui/command/index")['CommandEmpty']>
    'LazyUiCommandGroup': LazyComponent<typeof import("../../components/ui/command/index")['CommandGroup']>
    'LazyUiCommandInput': LazyComponent<typeof import("../../components/ui/command/index")['CommandInput']>
    'LazyUiCommandItem': LazyComponent<typeof import("../../components/ui/command/index")['CommandItem']>
    'LazyUiCommandList': LazyComponent<typeof import("../../components/ui/command/index")['CommandList']>
    'LazyUiCommandSeparator': LazyComponent<typeof import("../../components/ui/command/index")['CommandSeparator']>
    'LazyUiCommandShortcut': LazyComponent<typeof import("../../components/ui/command/index")['CommandShortcut']>
    'LazyUiDialog': LazyComponent<typeof import("../../components/ui/dialog/index")['Dialog']>
    'LazyUiDialogClose': LazyComponent<typeof import("../../components/ui/dialog/index")['DialogClose']>
    'LazyUiDialogContent': LazyComponent<typeof import("../../components/ui/dialog/index")['DialogContent']>
    'LazyUiDialogDescription': LazyComponent<typeof import("../../components/ui/dialog/index")['DialogDescription']>
    'LazyUiDialogFooter': LazyComponent<typeof import("../../components/ui/dialog/index")['DialogFooter']>
    'LazyUiDialogHeader': LazyComponent<typeof import("../../components/ui/dialog/index")['DialogHeader']>
    'LazyUiDialogOverlay': LazyComponent<typeof import("../../components/ui/dialog/index")['DialogOverlay']>
    'LazyUiDialogScrollContent': LazyComponent<typeof import("../../components/ui/dialog/index")['DialogScrollContent']>
    'LazyUiDialogTitle': LazyComponent<typeof import("../../components/ui/dialog/index")['DialogTitle']>
    'LazyUiDialogTrigger': LazyComponent<typeof import("../../components/ui/dialog/index")['DialogTrigger']>
    'LazyUiDropdownMenu': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenu']>
    'LazyUiDropdownMenuCheckboxItem': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
    'LazyUiDropdownMenuContent': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuContent']>
    'LazyUiDropdownMenuGroup': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuGroup']>
    'LazyUiDropdownMenuItem': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuItem']>
    'LazyUiDropdownMenuLabel': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuLabel']>
    'LazyUiDropdownMenuRadioGroup': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
    'LazyUiDropdownMenuRadioItem': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
    'LazyUiDropdownMenuSeparator': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
    'LazyUiDropdownMenuShortcut': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
    'LazyUiDropdownMenuSub': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSub']>
    'LazyUiDropdownMenuSubContent': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
    'LazyUiDropdownMenuSubTrigger': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
    'LazyUiDropdownMenuTrigger': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
    'LazyUiDropdownMenuPortal': LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuPortal']>
    'LazyUiFormControl': LazyComponent<typeof import("../../components/ui/form/index")['FormControl']>
    'LazyUiFormDescription': LazyComponent<typeof import("../../components/ui/form/index")['FormDescription']>
    'LazyUiFormItem': LazyComponent<typeof import("../../components/ui/form/index")['FormItem']>
    'LazyUiFormLabel': LazyComponent<typeof import("../../components/ui/form/index")['FormLabel']>
    'LazyUiFormMessage': LazyComponent<typeof import("../../components/ui/form/index")['FormMessage']>
    'LazyUiFORMITEMINJECTIONKEY': LazyComponent<typeof import("../../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']>
    'LazyUiForm': LazyComponent<typeof import("../../components/ui/form/index")['Form']>
    'LazyUiFormField': LazyComponent<typeof import("../../components/ui/form/index")['FormField']>
    'LazyUiFormFieldArray': LazyComponent<typeof import("../../components/ui/form/index")['FormFieldArray']>
    'LazyUiInput': LazyComponent<typeof import("../../components/ui/input/index")['Input']>
    'LazyUiLabel': LazyComponent<typeof import("../../components/ui/label/index")['Label']>
    'LazyUiPopover': LazyComponent<typeof import("../../components/ui/popover/index")['Popover']>
    'LazyUiPopoverAnchor': LazyComponent<typeof import("../../components/ui/popover/index")['PopoverAnchor']>
    'LazyUiPopoverContent': LazyComponent<typeof import("../../components/ui/popover/index")['PopoverContent']>
    'LazyUiPopoverTrigger': LazyComponent<typeof import("../../components/ui/popover/index")['PopoverTrigger']>
    'LazyUiSelect': LazyComponent<typeof import("../../components/ui/select/index")['Select']>
    'LazyUiSelectContent': LazyComponent<typeof import("../../components/ui/select/index")['SelectContent']>
    'LazyUiSelectGroup': LazyComponent<typeof import("../../components/ui/select/index")['SelectGroup']>
    'LazyUiSelectItem': LazyComponent<typeof import("../../components/ui/select/index")['SelectItem']>
    'LazyUiSelectItemText': LazyComponent<typeof import("../../components/ui/select/index")['SelectItemText']>
    'LazyUiSelectLabel': LazyComponent<typeof import("../../components/ui/select/index")['SelectLabel']>
    'LazyUiSelectScrollDownButton': LazyComponent<typeof import("../../components/ui/select/index")['SelectScrollDownButton']>
    'LazyUiSelectScrollUpButton': LazyComponent<typeof import("../../components/ui/select/index")['SelectScrollUpButton']>
    'LazyUiSelectSeparator': LazyComponent<typeof import("../../components/ui/select/index")['SelectSeparator']>
    'LazyUiSelectTrigger': LazyComponent<typeof import("../../components/ui/select/index")['SelectTrigger']>
    'LazyUiSelectValue': LazyComponent<typeof import("../../components/ui/select/index")['SelectValue']>
    'LazyUiSkeleton': LazyComponent<typeof import("../../components/ui/skeleton/index")['Skeleton']>
    'LazyUiToaster': LazyComponent<typeof import("../../components/ui/sonner/index")['Toaster']>
    'LazyUiTable': LazyComponent<typeof import("../../components/ui/table/index")['Table']>
    'LazyUiTableBody': LazyComponent<typeof import("../../components/ui/table/index")['TableBody']>
    'LazyUiTableCaption': LazyComponent<typeof import("../../components/ui/table/index")['TableCaption']>
    'LazyUiTableCell': LazyComponent<typeof import("../../components/ui/table/index")['TableCell']>
    'LazyUiTableEmpty': LazyComponent<typeof import("../../components/ui/table/index")['TableEmpty']>
    'LazyUiTableFooter': LazyComponent<typeof import("../../components/ui/table/index")['TableFooter']>
    'LazyUiTableHead': LazyComponent<typeof import("../../components/ui/table/index")['TableHead']>
    'LazyUiTableHeader': LazyComponent<typeof import("../../components/ui/table/index")['TableHeader']>
    'LazyUiTableRow': LazyComponent<typeof import("../../components/ui/table/index")['TableRow']>
    'LazyUiTabs': LazyComponent<typeof import("../../components/ui/tabs/index")['Tabs']>
    'LazyUiTabsContent': LazyComponent<typeof import("../../components/ui/tabs/index")['TabsContent']>
    'LazyUiTabsList': LazyComponent<typeof import("../../components/ui/tabs/index")['TabsList']>
    'LazyUiTabsTrigger': LazyComponent<typeof import("../../components/ui/tabs/index")['TabsTrigger']>
    'LazyUiTextarea': LazyComponent<typeof import("../../components/ui/textarea/index")['Textarea']>
    'LazyUiTooltip': LazyComponent<typeof import("../../components/ui/tooltip/index")['Tooltip']>
    'LazyUiTooltipContent': LazyComponent<typeof import("../../components/ui/tooltip/index")['TooltipContent']>
    'LazyUiTooltipProvider': LazyComponent<typeof import("../../components/ui/tooltip/index")['TooltipProvider']>
    'LazyUiTooltipTrigger': LazyComponent<typeof import("../../components/ui/tooltip/index")['TooltipTrigger']>
    'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
    'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
    'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
    'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
    'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
    'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
    'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
    'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
    'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
    'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
    'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
    'LazyAppICDBrowser': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
