
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)


export const Breadcrumb: typeof import("../components/ui/breadcrumb/Breadcrumb.vue")['default']
export const BreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/BreadcrumbEllipsis.vue")['default']
export const BreadcrumbItem: typeof import("../components/ui/breadcrumb/BreadcrumbItem.vue")['default']
export const BreadcrumbLink: typeof import("../components/ui/breadcrumb/BreadcrumbLink.vue")['default']
export const BreadcrumbList: typeof import("../components/ui/breadcrumb/BreadcrumbList.vue")['default']
export const BreadcrumbPage: typeof import("../components/ui/breadcrumb/BreadcrumbPage.vue")['default']
export const BreadcrumbSeparator: typeof import("../components/ui/breadcrumb/BreadcrumbSeparator.vue")['default']
export const Button: typeof import("../components/ui/button/Button.vue")['default']
export const Calendar: typeof import("../components/ui/calendar/Calendar.vue")['default']
export const CalendarCell: typeof import("../components/ui/calendar/CalendarCell.vue")['default']
export const CalendarCellTrigger: typeof import("../components/ui/calendar/CalendarCellTrigger.vue")['default']
export const CalendarGrid: typeof import("../components/ui/calendar/CalendarGrid.vue")['default']
export const CalendarGridBody: typeof import("../components/ui/calendar/CalendarGridBody.vue")['default']
export const CalendarGridHead: typeof import("../components/ui/calendar/CalendarGridHead.vue")['default']
export const CalendarGridRow: typeof import("../components/ui/calendar/CalendarGridRow.vue")['default']
export const CalendarHeadCell: typeof import("../components/ui/calendar/CalendarHeadCell.vue")['default']
export const CalendarHeader: typeof import("../components/ui/calendar/CalendarHeader.vue")['default']
export const CalendarHeading: typeof import("../components/ui/calendar/CalendarHeading.vue")['default']
export const CalendarNextButton: typeof import("../components/ui/calendar/CalendarNextButton.vue")['default']
export const CalendarPrevButton: typeof import("../components/ui/calendar/CalendarPrevButton.vue")['default']
export const Card: typeof import("../components/ui/card/Card.vue")['default']
export const CardAction: typeof import("../components/ui/card/CardAction.vue")['default']
export const CardContent: typeof import("../components/ui/card/CardContent.vue")['default']
export const CardDescription: typeof import("../components/ui/card/CardDescription.vue")['default']
export const CardFooter: typeof import("../components/ui/card/CardFooter.vue")['default']
export const CardHeader: typeof import("../components/ui/card/CardHeader.vue")['default']
export const CardTitle: typeof import("../components/ui/card/CardTitle.vue")['default']
export const Checkbox: typeof import("../components/ui/checkbox/Checkbox.vue")['default']
export const Combobox: typeof import("../components/ui/combobox/Combobox.vue")['default']
export const ComboboxAnchor: typeof import("../components/ui/combobox/ComboboxAnchor.vue")['default']
export const ComboboxEmpty: typeof import("../components/ui/combobox/ComboboxEmpty.vue")['default']
export const ComboboxGroup: typeof import("../components/ui/combobox/ComboboxGroup.vue")['default']
export const ComboboxInput: typeof import("../components/ui/combobox/ComboboxInput.vue")['default']
export const ComboboxItem: typeof import("../components/ui/combobox/ComboboxItem.vue")['default']
export const ComboboxItemIndicator: typeof import("../components/ui/combobox/ComboboxItemIndicator.vue")['default']
export const ComboboxList: typeof import("../components/ui/combobox/ComboboxList.vue")['default']
export const ComboboxSeparator: typeof import("../components/ui/combobox/ComboboxSeparator.vue")['default']
export const ComboboxTrigger: typeof import("../components/ui/combobox/ComboboxTrigger.vue")['default']
export const ComboboxViewport: typeof import("../components/ui/combobox/ComboboxViewport.vue")['default']
export const Command: typeof import("../components/ui/command/Command.vue")['default']
export const CommandDialog: typeof import("../components/ui/command/CommandDialog.vue")['default']
export const CommandEmpty: typeof import("../components/ui/command/CommandEmpty.vue")['default']
export const CommandGroup: typeof import("../components/ui/command/CommandGroup.vue")['default']
export const CommandInput: typeof import("../components/ui/command/CommandInput.vue")['default']
export const CommandItem: typeof import("../components/ui/command/CommandItem.vue")['default']
export const CommandList: typeof import("../components/ui/command/CommandList.vue")['default']
export const CommandSeparator: typeof import("../components/ui/command/CommandSeparator.vue")['default']
export const CommandShortcut: typeof import("../components/ui/command/CommandShortcut.vue")['default']
export const Dialog: typeof import("../components/ui/dialog/Dialog.vue")['default']
export const DialogClose: typeof import("../components/ui/dialog/DialogClose.vue")['default']
export const DialogContent: typeof import("../components/ui/dialog/DialogContent.vue")['default']
export const DialogDescription: typeof import("../components/ui/dialog/DialogDescription.vue")['default']
export const DialogFooter: typeof import("../components/ui/dialog/DialogFooter.vue")['default']
export const DialogHeader: typeof import("../components/ui/dialog/DialogHeader.vue")['default']
export const DialogOverlay: typeof import("../components/ui/dialog/DialogOverlay.vue")['default']
export const DialogScrollContent: typeof import("../components/ui/dialog/DialogScrollContent.vue")['default']
export const DialogTitle: typeof import("../components/ui/dialog/DialogTitle.vue")['default']
export const DialogTrigger: typeof import("../components/ui/dialog/DialogTrigger.vue")['default']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/DropdownMenu.vue")['default']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/DropdownMenuContent.vue")['default']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/DropdownMenuItem.vue")['default']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/DropdownMenuSub.vue")['default']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']
export const FormControl: typeof import("../components/ui/form/FormControl.vue")['default']
export const FormDescription: typeof import("../components/ui/form/FormDescription.vue")['default']
export const FormItem: typeof import("../components/ui/form/FormItem.vue")['default']
export const FormLabel: typeof import("../components/ui/form/FormLabel.vue")['default']
export const FormMessage: typeof import("../components/ui/form/FormMessage.vue")['default']
export const Form: typeof import("../components/ui/form/index")['default']
export const FormInjectionKeys: typeof import("../components/ui/form/injectionKeys")['default']
export const FormUseFormField: typeof import("../components/ui/form/useFormField")['default']
export const Input: typeof import("../components/ui/input/Input.vue")['default']
export const Label: typeof import("../components/ui/label/Label.vue")['default']
export const Popover: typeof import("../components/ui/popover/Popover.vue")['default']
export const PopoverAnchor: typeof import("../components/ui/popover/PopoverAnchor.vue")['default']
export const PopoverContent: typeof import("../components/ui/popover/PopoverContent.vue")['default']
export const PopoverTrigger: typeof import("../components/ui/popover/PopoverTrigger.vue")['default']
export const Select: typeof import("../components/ui/select/Select.vue")['default']
export const SelectContent: typeof import("../components/ui/select/SelectContent.vue")['default']
export const SelectGroup: typeof import("../components/ui/select/SelectGroup.vue")['default']
export const SelectItem: typeof import("../components/ui/select/SelectItem.vue")['default']
export const SelectItemText: typeof import("../components/ui/select/SelectItemText.vue")['default']
export const SelectLabel: typeof import("../components/ui/select/SelectLabel.vue")['default']
export const SelectScrollDownButton: typeof import("../components/ui/select/SelectScrollDownButton.vue")['default']
export const SelectScrollUpButton: typeof import("../components/ui/select/SelectScrollUpButton.vue")['default']
export const SelectSeparator: typeof import("../components/ui/select/SelectSeparator.vue")['default']
export const SelectTrigger: typeof import("../components/ui/select/SelectTrigger.vue")['default']
export const SelectValue: typeof import("../components/ui/select/SelectValue.vue")['default']
export const Skeleton: typeof import("../components/ui/skeleton/Skeleton.vue")['default']
export const Sonner: typeof import("../components/ui/sonner/Sonner.vue")['default']
export const Table: typeof import("../components/ui/table/Table.vue")['default']
export const TableBody: typeof import("../components/ui/table/TableBody.vue")['default']
export const TableCaption: typeof import("../components/ui/table/TableCaption.vue")['default']
export const TableCell: typeof import("../components/ui/table/TableCell.vue")['default']
export const TableEmpty: typeof import("../components/ui/table/TableEmpty.vue")['default']
export const TableFooter: typeof import("../components/ui/table/TableFooter.vue")['default']
export const TableHead: typeof import("../components/ui/table/TableHead.vue")['default']
export const TableHeader: typeof import("../components/ui/table/TableHeader.vue")['default']
export const TableRow: typeof import("../components/ui/table/TableRow.vue")['default']
export const TableUtils: typeof import("../components/ui/table/utils")['default']
export const Tabs: typeof import("../components/ui/tabs/Tabs.vue")['default']
export const TabsContent: typeof import("../components/ui/tabs/TabsContent.vue")['default']
export const TabsList: typeof import("../components/ui/tabs/TabsList.vue")['default']
export const TabsTrigger: typeof import("../components/ui/tabs/TabsTrigger.vue")['default']
export const Textarea: typeof import("../components/ui/textarea/Textarea.vue")['default']
export const Tooltip: typeof import("../components/ui/tooltip/Tooltip.vue")['default']
export const TooltipContent: typeof import("../components/ui/tooltip/TooltipContent.vue")['default']
export const TooltipProvider: typeof import("../components/ui/tooltip/TooltipProvider.vue")['default']
export const TooltipTrigger: typeof import("../components/ui/tooltip/TooltipTrigger.vue")['default']
export const AdminDashboardAdminStatsCards: typeof import("../components/admin/dashboard/AdminStatsCards.vue")['default']
export const AdminDashboardAdminWelcomeHeader: typeof import("../components/admin/dashboard/AdminWelcomeHeader.vue")['default']
export const AdminDashboardAnalyticsChart: typeof import("../components/admin/dashboard/AnalyticsChart.vue")['default']
export const AdminDashboardSystemMetrics: typeof import("../components/admin/dashboard/SystemMetrics.vue")['default']
export const AdminDashboardUserManagement: typeof import("../components/admin/dashboard/UserManagement.vue")['default']
export const AppFormTypedCheckbox: typeof import("../components/app/form/TypedCheckbox.vue")['default']
export const AppFormTypedCombobox: typeof import("../components/app/form/TypedCombobox.vue")['default']
export const AppFormTypedDate: typeof import("../components/app/form/TypedDate.vue")['default']
export const AppFormTypedDatetime: typeof import("../components/app/form/TypedDatetime.vue")['default']
export const AppFormTypedFile: typeof import("../components/app/form/TypedFile.vue")['default']
export const AppFormTypedForm: typeof import("../components/app/form/TypedForm.vue")['default']
export const AppFormTypedInput: typeof import("../components/app/form/TypedInput.vue")['default']
export const AppFormTypedNumber: typeof import("../components/app/form/TypedNumber.vue")['default']
export const AppFormTypedSelect: typeof import("../components/app/form/TypedSelect.vue")['default']
export const AppFormTypedTextarea: typeof import("../components/app/form/TypedTextarea.vue")['default']
export const AppFormTypedTime: typeof import("../components/app/form/TypedTime.vue")['default']
export const AppForm: typeof import("../components/app/form/index")['default']
export const AppICDBrowser: typeof import("../components/app/icd/ICDBrowser.client.vue")['default']
export const AppIcd: typeof import("../components/app/icd/index")['default']
export const AppOCRCanvas: typeof import("../components/app/ocr/OCRCanvas.vue")['default']
export const AppOCRDialog: typeof import("../components/app/ocr/OCRDialog.vue")['default']
export const AppOcr: typeof import("../components/app/ocr/index")['default']
export const AppQrcodeQRCodeDisplay: typeof import("../components/app/qrcode/QRCodeDisplay.vue")['default']
export const AppQrcodeQRCodeScanner: typeof import("../components/app/qrcode/QRCodeScanner.vue")['default']
export const AppQrcode: typeof import("../components/app/qrcode/index")['default']
export const AppReportsLineChartTile: typeof import("../components/app/reports/LineChartTile.vue")['default']
export const AppReportsNumericTile: typeof import("../components/app/reports/NumericTile.vue")['default']
export const AppReportsPieChartTile: typeof import("../components/app/reports/PieChartTile.vue")['default']
export const AppReports: typeof import("../components/app/reports/index")['default']
export const LayoutBreadcrumbsPageBreadcrumbs: typeof import("../components/layout/breadcrumbs/PageBreadcrumbs.vue")['default']
export const LayoutBreadcrumbs: typeof import("../components/layout/breadcrumbs/index")['default']
export const LayoutCommandDialog: typeof import("../components/layout/command/CommandDialog.vue")['default']
export const LayoutCommandGroup: typeof import("../components/layout/command/CommandGroup.vue")['default']
export const LayoutCommandPalette: typeof import("../components/layout/command/CommandPalette.vue")['default']
export const LayoutCommand: typeof import("../components/layout/command/index")['default']
export const LayoutNotificationsPopover: typeof import("../components/layout/notifications/NotificationsPopover.vue")['default']
export const LayoutNotifications: typeof import("../components/layout/notifications/index")['default']
export const LayoutSidebarBase: typeof import("../components/layout/sidebar/SidebarBase.vue")['default']
export const LayoutSidebarFooter: typeof import("../components/layout/sidebar/SidebarFooter.vue")['default']
export const LayoutSidebarGroup: typeof import("../components/layout/sidebar/SidebarGroup.vue")['default']
export const LayoutSidebarHeader: typeof import("../components/layout/sidebar/SidebarHeader.vue")['default']
export const LayoutSidebarItem: typeof import("../components/layout/sidebar/SidebarItem.vue")['default']
export const LayoutSidebar: typeof import("../components/layout/sidebar/index")['default']
export const StaffDashboardAnalyticsChart: typeof import("../components/staff/dashboard/AnalyticsChart.vue")['default']
export const StaffDashboardRecentActivities: typeof import("../components/staff/dashboard/RecentActivities.vue")['default']
export const StaffDashboardStatsCards: typeof import("../components/staff/dashboard/StatsCards.vue")['default']
export const StaffDashboardTodaysAppointments: typeof import("../components/staff/dashboard/TodaysAppointments.vue")['default']
export const StaffDashboardWelcomeHeader: typeof import("../components/staff/dashboard/WelcomeHeader.vue")['default']
export const AboutUsForm: typeof import("../pages/(public)/platform/components/AboutUsForm.vue")['default']
export const EnterpriseForm: typeof import("../pages/(public)/platform/components/EnterpriseForm.vue")['default']
export const LoginForm: typeof import("../pages/(public)/platform/components/LoginForm.vue")['default']
export const PrivacyPolicyForm: typeof import("../pages/(public)/platform/components/PrivacyPolicyForm.vue")['default']
export const ProfessionalForm: typeof import("../pages/(public)/platform/components/ProfessionalForm.vue")['default']
export const ServicesForm: typeof import("../pages/(public)/platform/components/ServicesForm.vue")['default']
export const SignUpForm: typeof import("../pages/(public)/platform/components/SignUpForm.vue")['default']
export const StartUpForm: typeof import("../pages/(public)/platform/components/StartUpForm.vue")['default']
export const SupportForm: typeof import("../pages/(public)/platform/components/SupportForm.vue")['default']
export const TermsOfUseForm: typeof import("../pages/(public)/platform/components/TermsOfUseForm.vue")['default']
export const LogEntityCell: typeof import("../pages/admin/logs/components/LogEntityCell.vue")['default']
export const LogsTable: typeof import("../pages/admin/logs/components/LogsTable.vue")['default']
export const UserProfileForm: typeof import("../pages/admin/users/components/UserProfileForm.vue")['default']
export const IndexDashboard: typeof import("../pages/index/components/IndexDashboard.vue")['default']
export const ClaimRequestForm: typeof import("../pages/partner/components/ClaimRequestForm.vue")['default']
export const ClaimRequestsTable: typeof import("../pages/partner/components/ClaimRequestsTable.vue")['default']
export const DataRequestForm: typeof import("../pages/partner/components/DataRequestForm.vue")['default']
export const DataRequestsTable: typeof import("../pages/partner/components/DataRequestsTable.vue")['default']
export const PartnerForm: typeof import("../pages/partner/components/PartnerForm.vue")['default']
export const PartnerTable: typeof import("../pages/partner/components/PartnerTable.vue")['default']
export const PatientAppointmentFilters: typeof import("../pages/patient/appointments/components/PatientAppointmentFilters.vue")['default']
export const PatientAppointmentForm: typeof import("../pages/patient/appointments/components/PatientAppointmentForm.vue")['default']
export const PatientAppointmentsAvailability: typeof import("../pages/patient/appointments/components/PatientAppointmentsAvailability.vue")['default']
export const PatientAppointmentsTable: typeof import("../pages/patient/appointments/components/PatientAppointmentsTable.vue")['default']
export const PatientsBillingTable: typeof import("../pages/patient/billing/components/PatientsBillingTable.vue")['default']
export const DoctorTable: typeof import("../pages/patient/doctor/components/DoctorTable.vue")['default']
export const MedicalRecordForm: typeof import("../pages/patient/medical-records/components/MedicalRecordForm.vue")['default']
export const MedicalRecordsTable: typeof import("../pages/patient/medical-records/components/MedicalRecordsTable.vue")['default']
export const AppointmentFilters: typeof import("../pages/staff/appointments/components/AppointmentFilters.vue")['default']
export const AppointmentForm: typeof import("../pages/staff/appointments/components/AppointmentForm.vue")['default']
export const AppointmentsAvailability: typeof import("../pages/staff/appointments/components/AppointmentsAvailability.vue")['default']
export const AppointmentsTable: typeof import("../pages/staff/appointments/components/AppointmentsTable.vue")['default']
export const BillingPaymentForm: typeof import("../pages/staff/billing/components/BillingPaymentForm.vue")['default']
export const BillingPaymentInstalmentForm: typeof import("../pages/staff/billing/components/BillingPaymentInstalmentForm.vue")['default']
export const BillingPaymentInstalmentTable: typeof import("../pages/staff/billing/components/BillingPaymentInstalmentTable.vue")['default']
export const BillingPaymentPlanForm: typeof import("../pages/staff/billing/components/BillingPaymentPlanForm.vue")['default']
export const BillingPaymentPlansTable: typeof import("../pages/staff/billing/components/BillingPaymentPlansTable.vue")['default']
export const BillingPaymentsTable: typeof import("../pages/staff/billing/components/BillingPaymentsTable.vue")['default']
export const BillingTransactionForm: typeof import("../pages/staff/billing/components/BillingTransactionForm.vue")['default']
export const BillingTransactionItemForm: typeof import("../pages/staff/billing/components/BillingTransactionItemForm.vue")['default']
export const BillingTransactionItemsTable: typeof import("../pages/staff/billing/components/BillingTransactionItemsTable.vue")['default']
export const BillingTransactionsTable: typeof import("../pages/staff/billing/components/BillingTransactionsTable.vue")['default']
export const AppointmentsList: typeof import("../pages/staff/dashboard/components/AppointmentsList.vue")['default']
export const DashboardFilters: typeof import("../pages/staff/dashboard/components/DashboardFilters.vue")['default']
export const DashboardSummaryCards: typeof import("../pages/staff/dashboard/components/DashboardSummaryCards.vue")['default']
export const DoctorDashboard: typeof import("../pages/staff/dashboard/components/DoctorDashboard.vue")['default']
export const SecretaryDashboard: typeof import("../pages/staff/dashboard/components/SecretaryDashboard.vue")['default']
export const BuildingForm: typeof import("../pages/staff/facilities/components/BuildingForm.vue")['default']
export const BuildingsTable: typeof import("../pages/staff/facilities/components/BuildingsTable.vue")['default']
export const FacilitiesTable: typeof import("../pages/staff/facilities/components/FacilitiesTable.vue")['default']
export const FacilityForm: typeof import("../pages/staff/facilities/components/FacilityForm.vue")['default']
export const FacilityLogsTable: typeof import("../pages/staff/facilities/components/FacilityLogsTable.vue")['default']
export const InsuranceClaimForm: typeof import("../pages/staff/insurance/components/InsuranceClaimForm.vue")['default']
export const InsuranceClaimItemForm: typeof import("../pages/staff/insurance/components/InsuranceClaimItemForm.vue")['default']
export const InsuranceClaimItemsTable: typeof import("../pages/staff/insurance/components/InsuranceClaimItemsTable.vue")['default']
export const InsuranceClaimsTable: typeof import("../pages/staff/insurance/components/InsuranceClaimsTable.vue")['default']
export const InsuranceProviderForm: typeof import("../pages/staff/insurance/components/InsuranceProviderForm.vue")['default']
export const InsuranceProviderTable: typeof import("../pages/staff/insurance/components/InsuranceProviderTable.vue")['default']
export const EncountersModule: typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/EncountersModule.vue")['default']
export const InpatientForm: typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/InpatientForm.vue")['default']
export const OutpatientForm: typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/OutpatientForm.vue")['default']
export const EncountersTable: typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/components/EncountersTable.vue")['default']
export const InpatientTable: typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/components/InpatientTable.vue")['default']
export const OutpatientTable: typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/components/OutpatientTable.vue")['default']
export const [inpatientEncounterId]: typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/inpatient/[inpatientEncounterId].vue")['default']
export const [outpatientEncounterId]: typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/outpatient/[outpatientEncounterId].vue")['default']
export const New: typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/outpatient/new.vue")['default']
export const AddressFields: typeof import("../pages/staff/patients/components/AddressFields.vue")['default']
export const ConsentFields: typeof import("../pages/staff/patients/components/ConsentFields.vue")['default']
export const ContactFields: typeof import("../pages/staff/patients/components/ContactFields.vue")['default']
export const EmergencyContactFields: typeof import("../pages/staff/patients/components/EmergencyContactFields.vue")['default']
export const EmploymentFields: typeof import("../pages/staff/patients/components/EmploymentFields.vue")['default']
export const PatientProfileForm: typeof import("../pages/staff/patients/components/PatientProfileForm.vue")['default']
export const PatientProfileTable: typeof import("../pages/staff/patients/components/PatientProfileTable.vue")['default']
export const ProfileFields: typeof import("../pages/staff/patients/components/ProfileFields.vue")['default']
export const PharmacyBrandForm: typeof import("../pages/staff/pharmacy/components/PharmacyBrandForm.vue")['default']
export const PharmacyBrandsTable: typeof import("../pages/staff/pharmacy/components/PharmacyBrandsTable.vue")['default']
export const PharmacyCategoriesTable: typeof import("../pages/staff/pharmacy/components/PharmacyCategoriesTable.vue")['default']
export const PharmacyCategoryForm: typeof import("../pages/staff/pharmacy/components/PharmacyCategoryForm.vue")['default']
export const PharmacyItemForm: typeof import("../pages/staff/pharmacy/components/PharmacyItemForm.vue")['default']
export const PharmacyItemsTable: typeof import("../pages/staff/pharmacy/components/PharmacyItemsTable.vue")['default']
export const PharmacySupplierForm: typeof import("../pages/staff/pharmacy/components/PharmacySupplierForm.vue")['default']
export const PharmacySuppliersTable: typeof import("../pages/staff/pharmacy/components/PharmacySuppliersTable.vue")['default']
export const StaffForm: typeof import("../pages/staff/staff/components/StaffForm.vue")['default']
export const StaffTable: typeof import("../pages/staff/staff/components/StaffTable.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const UiBreadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const UiBreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const UiBreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const UiBreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const UiBreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const UiBreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const UiBreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const UiButton: typeof import("../components/ui/button/index")['Button']
export const UiCalendar: typeof import("../components/ui/calendar/index")['Calendar']
export const UiCalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const UiCalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const UiCalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const UiCalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const UiCalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const UiCalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const UiCalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const UiCalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const UiCalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const UiCalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const UiCalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const UiCard: typeof import("../components/ui/card/index")['Card']
export const UiCardAction: typeof import("../components/ui/card/index")['CardAction']
export const UiCardContent: typeof import("../components/ui/card/index")['CardContent']
export const UiCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const UiCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const UiCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const UiCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const UiCheckbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const UiCombobox: typeof import("../components/ui/combobox/index")['Combobox']
export const UiComboboxAnchor: typeof import("../components/ui/combobox/index")['ComboboxAnchor']
export const UiComboboxEmpty: typeof import("../components/ui/combobox/index")['ComboboxEmpty']
export const UiComboboxGroup: typeof import("../components/ui/combobox/index")['ComboboxGroup']
export const UiComboboxInput: typeof import("../components/ui/combobox/index")['ComboboxInput']
export const UiComboboxItem: typeof import("../components/ui/combobox/index")['ComboboxItem']
export const UiComboboxItemIndicator: typeof import("../components/ui/combobox/index")['ComboboxItemIndicator']
export const UiComboboxList: typeof import("../components/ui/combobox/index")['ComboboxList']
export const UiComboboxSeparator: typeof import("../components/ui/combobox/index")['ComboboxSeparator']
export const UiComboboxTrigger: typeof import("../components/ui/combobox/index")['ComboboxTrigger']
export const UiComboboxViewport: typeof import("../components/ui/combobox/index")['ComboboxViewport']
export const UiComboboxCancel: typeof import("../components/ui/combobox/index")['ComboboxCancel']
export const UiCommand: typeof import("../components/ui/command/index")['Command']
export const UiCommandDialog: typeof import("../components/ui/command/index")['CommandDialog']
export const UiCommandEmpty: typeof import("../components/ui/command/index")['CommandEmpty']
export const UiCommandGroup: typeof import("../components/ui/command/index")['CommandGroup']
export const UiCommandInput: typeof import("../components/ui/command/index")['CommandInput']
export const UiCommandItem: typeof import("../components/ui/command/index")['CommandItem']
export const UiCommandList: typeof import("../components/ui/command/index")['CommandList']
export const UiCommandSeparator: typeof import("../components/ui/command/index")['CommandSeparator']
export const UiCommandShortcut: typeof import("../components/ui/command/index")['CommandShortcut']
export const UiDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const UiDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const UiDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const UiDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const UiDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const UiDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const UiDialogOverlay: typeof import("../components/ui/dialog/index")['DialogOverlay']
export const UiDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const UiDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const UiDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const UiDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const UiDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const UiDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const UiDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const UiDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const UiDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const UiDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const UiDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const UiDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const UiDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const UiDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const UiDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const UiDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const UiDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const UiDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const UiFormControl: typeof import("../components/ui/form/index")['FormControl']
export const UiFormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const UiFormItem: typeof import("../components/ui/form/index")['FormItem']
export const UiFormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const UiFormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const UiFORMITEMINJECTIONKEY: typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const UiForm: typeof import("../components/ui/form/index")['Form']
export const UiFormField: typeof import("../components/ui/form/index")['FormField']
export const UiFormFieldArray: typeof import("../components/ui/form/index")['FormFieldArray']
export const UiInput: typeof import("../components/ui/input/index")['Input']
export const UiLabel: typeof import("../components/ui/label/index")['Label']
export const UiPopover: typeof import("../components/ui/popover/index")['Popover']
export const UiPopoverAnchor: typeof import("../components/ui/popover/index")['PopoverAnchor']
export const UiPopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const UiPopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const UiSelect: typeof import("../components/ui/select/index")['Select']
export const UiSelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const UiSelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const UiSelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const UiSelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const UiSelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const UiSelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const UiSelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const UiSelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const UiSelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const UiSelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const UiSkeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const UiToaster: typeof import("../components/ui/sonner/index")['Toaster']
export const UiTable: typeof import("../components/ui/table/index")['Table']
export const UiTableBody: typeof import("../components/ui/table/index")['TableBody']
export const UiTableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const UiTableCell: typeof import("../components/ui/table/index")['TableCell']
export const UiTableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const UiTableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const UiTableHead: typeof import("../components/ui/table/index")['TableHead']
export const UiTableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const UiTableRow: typeof import("../components/ui/table/index")['TableRow']
export const UiTabs: typeof import("../components/ui/tabs/index")['Tabs']
export const UiTabsContent: typeof import("../components/ui/tabs/index")['TabsContent']
export const UiTabsList: typeof import("../components/ui/tabs/index")['TabsList']
export const UiTabsTrigger: typeof import("../components/ui/tabs/index")['TabsTrigger']
export const UiTextarea: typeof import("../components/ui/textarea/index")['Textarea']
export const UiTooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const UiTooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const UiTooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const UiTooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const AppICDBrowser: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyBreadcrumb: LazyComponent<typeof import("../components/ui/breadcrumb/Breadcrumb.vue")['default']>
export const LazyBreadcrumbEllipsis: LazyComponent<typeof import("../components/ui/breadcrumb/BreadcrumbEllipsis.vue")['default']>
export const LazyBreadcrumbItem: LazyComponent<typeof import("../components/ui/breadcrumb/BreadcrumbItem.vue")['default']>
export const LazyBreadcrumbLink: LazyComponent<typeof import("../components/ui/breadcrumb/BreadcrumbLink.vue")['default']>
export const LazyBreadcrumbList: LazyComponent<typeof import("../components/ui/breadcrumb/BreadcrumbList.vue")['default']>
export const LazyBreadcrumbPage: LazyComponent<typeof import("../components/ui/breadcrumb/BreadcrumbPage.vue")['default']>
export const LazyBreadcrumbSeparator: LazyComponent<typeof import("../components/ui/breadcrumb/BreadcrumbSeparator.vue")['default']>
export const LazyButton: LazyComponent<typeof import("../components/ui/button/Button.vue")['default']>
export const LazyCalendar: LazyComponent<typeof import("../components/ui/calendar/Calendar.vue")['default']>
export const LazyCalendarCell: LazyComponent<typeof import("../components/ui/calendar/CalendarCell.vue")['default']>
export const LazyCalendarCellTrigger: LazyComponent<typeof import("../components/ui/calendar/CalendarCellTrigger.vue")['default']>
export const LazyCalendarGrid: LazyComponent<typeof import("../components/ui/calendar/CalendarGrid.vue")['default']>
export const LazyCalendarGridBody: LazyComponent<typeof import("../components/ui/calendar/CalendarGridBody.vue")['default']>
export const LazyCalendarGridHead: LazyComponent<typeof import("../components/ui/calendar/CalendarGridHead.vue")['default']>
export const LazyCalendarGridRow: LazyComponent<typeof import("../components/ui/calendar/CalendarGridRow.vue")['default']>
export const LazyCalendarHeadCell: LazyComponent<typeof import("../components/ui/calendar/CalendarHeadCell.vue")['default']>
export const LazyCalendarHeader: LazyComponent<typeof import("../components/ui/calendar/CalendarHeader.vue")['default']>
export const LazyCalendarHeading: LazyComponent<typeof import("../components/ui/calendar/CalendarHeading.vue")['default']>
export const LazyCalendarNextButton: LazyComponent<typeof import("../components/ui/calendar/CalendarNextButton.vue")['default']>
export const LazyCalendarPrevButton: LazyComponent<typeof import("../components/ui/calendar/CalendarPrevButton.vue")['default']>
export const LazyCard: LazyComponent<typeof import("../components/ui/card/Card.vue")['default']>
export const LazyCardAction: LazyComponent<typeof import("../components/ui/card/CardAction.vue")['default']>
export const LazyCardContent: LazyComponent<typeof import("../components/ui/card/CardContent.vue")['default']>
export const LazyCardDescription: LazyComponent<typeof import("../components/ui/card/CardDescription.vue")['default']>
export const LazyCardFooter: LazyComponent<typeof import("../components/ui/card/CardFooter.vue")['default']>
export const LazyCardHeader: LazyComponent<typeof import("../components/ui/card/CardHeader.vue")['default']>
export const LazyCardTitle: LazyComponent<typeof import("../components/ui/card/CardTitle.vue")['default']>
export const LazyCheckbox: LazyComponent<typeof import("../components/ui/checkbox/Checkbox.vue")['default']>
export const LazyCombobox: LazyComponent<typeof import("../components/ui/combobox/Combobox.vue")['default']>
export const LazyComboboxAnchor: LazyComponent<typeof import("../components/ui/combobox/ComboboxAnchor.vue")['default']>
export const LazyComboboxEmpty: LazyComponent<typeof import("../components/ui/combobox/ComboboxEmpty.vue")['default']>
export const LazyComboboxGroup: LazyComponent<typeof import("../components/ui/combobox/ComboboxGroup.vue")['default']>
export const LazyComboboxInput: LazyComponent<typeof import("../components/ui/combobox/ComboboxInput.vue")['default']>
export const LazyComboboxItem: LazyComponent<typeof import("../components/ui/combobox/ComboboxItem.vue")['default']>
export const LazyComboboxItemIndicator: LazyComponent<typeof import("../components/ui/combobox/ComboboxItemIndicator.vue")['default']>
export const LazyComboboxList: LazyComponent<typeof import("../components/ui/combobox/ComboboxList.vue")['default']>
export const LazyComboboxSeparator: LazyComponent<typeof import("../components/ui/combobox/ComboboxSeparator.vue")['default']>
export const LazyComboboxTrigger: LazyComponent<typeof import("../components/ui/combobox/ComboboxTrigger.vue")['default']>
export const LazyComboboxViewport: LazyComponent<typeof import("../components/ui/combobox/ComboboxViewport.vue")['default']>
export const LazyCommand: LazyComponent<typeof import("../components/ui/command/Command.vue")['default']>
export const LazyCommandDialog: LazyComponent<typeof import("../components/ui/command/CommandDialog.vue")['default']>
export const LazyCommandEmpty: LazyComponent<typeof import("../components/ui/command/CommandEmpty.vue")['default']>
export const LazyCommandGroup: LazyComponent<typeof import("../components/ui/command/CommandGroup.vue")['default']>
export const LazyCommandInput: LazyComponent<typeof import("../components/ui/command/CommandInput.vue")['default']>
export const LazyCommandItem: LazyComponent<typeof import("../components/ui/command/CommandItem.vue")['default']>
export const LazyCommandList: LazyComponent<typeof import("../components/ui/command/CommandList.vue")['default']>
export const LazyCommandSeparator: LazyComponent<typeof import("../components/ui/command/CommandSeparator.vue")['default']>
export const LazyCommandShortcut: LazyComponent<typeof import("../components/ui/command/CommandShortcut.vue")['default']>
export const LazyDialog: LazyComponent<typeof import("../components/ui/dialog/Dialog.vue")['default']>
export const LazyDialogClose: LazyComponent<typeof import("../components/ui/dialog/DialogClose.vue")['default']>
export const LazyDialogContent: LazyComponent<typeof import("../components/ui/dialog/DialogContent.vue")['default']>
export const LazyDialogDescription: LazyComponent<typeof import("../components/ui/dialog/DialogDescription.vue")['default']>
export const LazyDialogFooter: LazyComponent<typeof import("../components/ui/dialog/DialogFooter.vue")['default']>
export const LazyDialogHeader: LazyComponent<typeof import("../components/ui/dialog/DialogHeader.vue")['default']>
export const LazyDialogOverlay: LazyComponent<typeof import("../components/ui/dialog/DialogOverlay.vue")['default']>
export const LazyDialogScrollContent: LazyComponent<typeof import("../components/ui/dialog/DialogScrollContent.vue")['default']>
export const LazyDialogTitle: LazyComponent<typeof import("../components/ui/dialog/DialogTitle.vue")['default']>
export const LazyDialogTrigger: LazyComponent<typeof import("../components/ui/dialog/DialogTrigger.vue")['default']>
export const LazyDropdownMenu: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenu.vue")['default']>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue")['default']>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuContent.vue")['default']>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuGroup.vue")['default']>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuItem.vue")['default']>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuLabel.vue")['default']>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuRadioGroup.vue")['default']>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuRadioItem.vue")['default']>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuSeparator.vue")['default']>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuShortcut.vue")['default']>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuSub.vue")['default']>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuSubContent.vue")['default']>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuSubTrigger.vue")['default']>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/DropdownMenuTrigger.vue")['default']>
export const LazyFormControl: LazyComponent<typeof import("../components/ui/form/FormControl.vue")['default']>
export const LazyFormDescription: LazyComponent<typeof import("../components/ui/form/FormDescription.vue")['default']>
export const LazyFormItem: LazyComponent<typeof import("../components/ui/form/FormItem.vue")['default']>
export const LazyFormLabel: LazyComponent<typeof import("../components/ui/form/FormLabel.vue")['default']>
export const LazyFormMessage: LazyComponent<typeof import("../components/ui/form/FormMessage.vue")['default']>
export const LazyForm: LazyComponent<typeof import("../components/ui/form/index")['default']>
export const LazyFormInjectionKeys: LazyComponent<typeof import("../components/ui/form/injectionKeys")['default']>
export const LazyFormUseFormField: LazyComponent<typeof import("../components/ui/form/useFormField")['default']>
export const LazyInput: LazyComponent<typeof import("../components/ui/input/Input.vue")['default']>
export const LazyLabel: LazyComponent<typeof import("../components/ui/label/Label.vue")['default']>
export const LazyPopover: LazyComponent<typeof import("../components/ui/popover/Popover.vue")['default']>
export const LazyPopoverAnchor: LazyComponent<typeof import("../components/ui/popover/PopoverAnchor.vue")['default']>
export const LazyPopoverContent: LazyComponent<typeof import("../components/ui/popover/PopoverContent.vue")['default']>
export const LazyPopoverTrigger: LazyComponent<typeof import("../components/ui/popover/PopoverTrigger.vue")['default']>
export const LazySelect: LazyComponent<typeof import("../components/ui/select/Select.vue")['default']>
export const LazySelectContent: LazyComponent<typeof import("../components/ui/select/SelectContent.vue")['default']>
export const LazySelectGroup: LazyComponent<typeof import("../components/ui/select/SelectGroup.vue")['default']>
export const LazySelectItem: LazyComponent<typeof import("../components/ui/select/SelectItem.vue")['default']>
export const LazySelectItemText: LazyComponent<typeof import("../components/ui/select/SelectItemText.vue")['default']>
export const LazySelectLabel: LazyComponent<typeof import("../components/ui/select/SelectLabel.vue")['default']>
export const LazySelectScrollDownButton: LazyComponent<typeof import("../components/ui/select/SelectScrollDownButton.vue")['default']>
export const LazySelectScrollUpButton: LazyComponent<typeof import("../components/ui/select/SelectScrollUpButton.vue")['default']>
export const LazySelectSeparator: LazyComponent<typeof import("../components/ui/select/SelectSeparator.vue")['default']>
export const LazySelectTrigger: LazyComponent<typeof import("../components/ui/select/SelectTrigger.vue")['default']>
export const LazySelectValue: LazyComponent<typeof import("../components/ui/select/SelectValue.vue")['default']>
export const LazySkeleton: LazyComponent<typeof import("../components/ui/skeleton/Skeleton.vue")['default']>
export const LazySonner: LazyComponent<typeof import("../components/ui/sonner/Sonner.vue")['default']>
export const LazyTable: LazyComponent<typeof import("../components/ui/table/Table.vue")['default']>
export const LazyTableBody: LazyComponent<typeof import("../components/ui/table/TableBody.vue")['default']>
export const LazyTableCaption: LazyComponent<typeof import("../components/ui/table/TableCaption.vue")['default']>
export const LazyTableCell: LazyComponent<typeof import("../components/ui/table/TableCell.vue")['default']>
export const LazyTableEmpty: LazyComponent<typeof import("../components/ui/table/TableEmpty.vue")['default']>
export const LazyTableFooter: LazyComponent<typeof import("../components/ui/table/TableFooter.vue")['default']>
export const LazyTableHead: LazyComponent<typeof import("../components/ui/table/TableHead.vue")['default']>
export const LazyTableHeader: LazyComponent<typeof import("../components/ui/table/TableHeader.vue")['default']>
export const LazyTableRow: LazyComponent<typeof import("../components/ui/table/TableRow.vue")['default']>
export const LazyTableUtils: LazyComponent<typeof import("../components/ui/table/utils")['default']>
export const LazyTabs: LazyComponent<typeof import("../components/ui/tabs/Tabs.vue")['default']>
export const LazyTabsContent: LazyComponent<typeof import("../components/ui/tabs/TabsContent.vue")['default']>
export const LazyTabsList: LazyComponent<typeof import("../components/ui/tabs/TabsList.vue")['default']>
export const LazyTabsTrigger: LazyComponent<typeof import("../components/ui/tabs/TabsTrigger.vue")['default']>
export const LazyTextarea: LazyComponent<typeof import("../components/ui/textarea/Textarea.vue")['default']>
export const LazyTooltip: LazyComponent<typeof import("../components/ui/tooltip/Tooltip.vue")['default']>
export const LazyTooltipContent: LazyComponent<typeof import("../components/ui/tooltip/TooltipContent.vue")['default']>
export const LazyTooltipProvider: LazyComponent<typeof import("../components/ui/tooltip/TooltipProvider.vue")['default']>
export const LazyTooltipTrigger: LazyComponent<typeof import("../components/ui/tooltip/TooltipTrigger.vue")['default']>
export const LazyAdminDashboardAdminStatsCards: LazyComponent<typeof import("../components/admin/dashboard/AdminStatsCards.vue")['default']>
export const LazyAdminDashboardAdminWelcomeHeader: LazyComponent<typeof import("../components/admin/dashboard/AdminWelcomeHeader.vue")['default']>
export const LazyAdminDashboardAnalyticsChart: LazyComponent<typeof import("../components/admin/dashboard/AnalyticsChart.vue")['default']>
export const LazyAdminDashboardSystemMetrics: LazyComponent<typeof import("../components/admin/dashboard/SystemMetrics.vue")['default']>
export const LazyAdminDashboardUserManagement: LazyComponent<typeof import("../components/admin/dashboard/UserManagement.vue")['default']>
export const LazyAppFormTypedCheckbox: LazyComponent<typeof import("../components/app/form/TypedCheckbox.vue")['default']>
export const LazyAppFormTypedCombobox: LazyComponent<typeof import("../components/app/form/TypedCombobox.vue")['default']>
export const LazyAppFormTypedDate: LazyComponent<typeof import("../components/app/form/TypedDate.vue")['default']>
export const LazyAppFormTypedDatetime: LazyComponent<typeof import("../components/app/form/TypedDatetime.vue")['default']>
export const LazyAppFormTypedFile: LazyComponent<typeof import("../components/app/form/TypedFile.vue")['default']>
export const LazyAppFormTypedForm: LazyComponent<typeof import("../components/app/form/TypedForm.vue")['default']>
export const LazyAppFormTypedInput: LazyComponent<typeof import("../components/app/form/TypedInput.vue")['default']>
export const LazyAppFormTypedNumber: LazyComponent<typeof import("../components/app/form/TypedNumber.vue")['default']>
export const LazyAppFormTypedSelect: LazyComponent<typeof import("../components/app/form/TypedSelect.vue")['default']>
export const LazyAppFormTypedTextarea: LazyComponent<typeof import("../components/app/form/TypedTextarea.vue")['default']>
export const LazyAppFormTypedTime: LazyComponent<typeof import("../components/app/form/TypedTime.vue")['default']>
export const LazyAppForm: LazyComponent<typeof import("../components/app/form/index")['default']>
export const LazyAppICDBrowser: LazyComponent<typeof import("../components/app/icd/ICDBrowser.client.vue")['default']>
export const LazyAppIcd: LazyComponent<typeof import("../components/app/icd/index")['default']>
export const LazyAppOCRCanvas: LazyComponent<typeof import("../components/app/ocr/OCRCanvas.vue")['default']>
export const LazyAppOCRDialog: LazyComponent<typeof import("../components/app/ocr/OCRDialog.vue")['default']>
export const LazyAppOcr: LazyComponent<typeof import("../components/app/ocr/index")['default']>
export const LazyAppQrcodeQRCodeDisplay: LazyComponent<typeof import("../components/app/qrcode/QRCodeDisplay.vue")['default']>
export const LazyAppQrcodeQRCodeScanner: LazyComponent<typeof import("../components/app/qrcode/QRCodeScanner.vue")['default']>
export const LazyAppQrcode: LazyComponent<typeof import("../components/app/qrcode/index")['default']>
export const LazyAppReportsLineChartTile: LazyComponent<typeof import("../components/app/reports/LineChartTile.vue")['default']>
export const LazyAppReportsNumericTile: LazyComponent<typeof import("../components/app/reports/NumericTile.vue")['default']>
export const LazyAppReportsPieChartTile: LazyComponent<typeof import("../components/app/reports/PieChartTile.vue")['default']>
export const LazyAppReports: LazyComponent<typeof import("../components/app/reports/index")['default']>
export const LazyLayoutBreadcrumbsPageBreadcrumbs: LazyComponent<typeof import("../components/layout/breadcrumbs/PageBreadcrumbs.vue")['default']>
export const LazyLayoutBreadcrumbs: LazyComponent<typeof import("../components/layout/breadcrumbs/index")['default']>
export const LazyLayoutCommandDialog: LazyComponent<typeof import("../components/layout/command/CommandDialog.vue")['default']>
export const LazyLayoutCommandGroup: LazyComponent<typeof import("../components/layout/command/CommandGroup.vue")['default']>
export const LazyLayoutCommandPalette: LazyComponent<typeof import("../components/layout/command/CommandPalette.vue")['default']>
export const LazyLayoutCommand: LazyComponent<typeof import("../components/layout/command/index")['default']>
export const LazyLayoutNotificationsPopover: LazyComponent<typeof import("../components/layout/notifications/NotificationsPopover.vue")['default']>
export const LazyLayoutNotifications: LazyComponent<typeof import("../components/layout/notifications/index")['default']>
export const LazyLayoutSidebarBase: LazyComponent<typeof import("../components/layout/sidebar/SidebarBase.vue")['default']>
export const LazyLayoutSidebarFooter: LazyComponent<typeof import("../components/layout/sidebar/SidebarFooter.vue")['default']>
export const LazyLayoutSidebarGroup: LazyComponent<typeof import("../components/layout/sidebar/SidebarGroup.vue")['default']>
export const LazyLayoutSidebarHeader: LazyComponent<typeof import("../components/layout/sidebar/SidebarHeader.vue")['default']>
export const LazyLayoutSidebarItem: LazyComponent<typeof import("../components/layout/sidebar/SidebarItem.vue")['default']>
export const LazyLayoutSidebar: LazyComponent<typeof import("../components/layout/sidebar/index")['default']>
export const LazyStaffDashboardAnalyticsChart: LazyComponent<typeof import("../components/staff/dashboard/AnalyticsChart.vue")['default']>
export const LazyStaffDashboardRecentActivities: LazyComponent<typeof import("../components/staff/dashboard/RecentActivities.vue")['default']>
export const LazyStaffDashboardStatsCards: LazyComponent<typeof import("../components/staff/dashboard/StatsCards.vue")['default']>
export const LazyStaffDashboardTodaysAppointments: LazyComponent<typeof import("../components/staff/dashboard/TodaysAppointments.vue")['default']>
export const LazyStaffDashboardWelcomeHeader: LazyComponent<typeof import("../components/staff/dashboard/WelcomeHeader.vue")['default']>
export const LazyAboutUsForm: LazyComponent<typeof import("../pages/(public)/platform/components/AboutUsForm.vue")['default']>
export const LazyEnterpriseForm: LazyComponent<typeof import("../pages/(public)/platform/components/EnterpriseForm.vue")['default']>
export const LazyLoginForm: LazyComponent<typeof import("../pages/(public)/platform/components/LoginForm.vue")['default']>
export const LazyPrivacyPolicyForm: LazyComponent<typeof import("../pages/(public)/platform/components/PrivacyPolicyForm.vue")['default']>
export const LazyProfessionalForm: LazyComponent<typeof import("../pages/(public)/platform/components/ProfessionalForm.vue")['default']>
export const LazyServicesForm: LazyComponent<typeof import("../pages/(public)/platform/components/ServicesForm.vue")['default']>
export const LazySignUpForm: LazyComponent<typeof import("../pages/(public)/platform/components/SignUpForm.vue")['default']>
export const LazyStartUpForm: LazyComponent<typeof import("../pages/(public)/platform/components/StartUpForm.vue")['default']>
export const LazySupportForm: LazyComponent<typeof import("../pages/(public)/platform/components/SupportForm.vue")['default']>
export const LazyTermsOfUseForm: LazyComponent<typeof import("../pages/(public)/platform/components/TermsOfUseForm.vue")['default']>
export const LazyLogEntityCell: LazyComponent<typeof import("../pages/admin/logs/components/LogEntityCell.vue")['default']>
export const LazyLogsTable: LazyComponent<typeof import("../pages/admin/logs/components/LogsTable.vue")['default']>
export const LazyUserProfileForm: LazyComponent<typeof import("../pages/admin/users/components/UserProfileForm.vue")['default']>
export const LazyIndexDashboard: LazyComponent<typeof import("../pages/index/components/IndexDashboard.vue")['default']>
export const LazyClaimRequestForm: LazyComponent<typeof import("../pages/partner/components/ClaimRequestForm.vue")['default']>
export const LazyClaimRequestsTable: LazyComponent<typeof import("../pages/partner/components/ClaimRequestsTable.vue")['default']>
export const LazyDataRequestForm: LazyComponent<typeof import("../pages/partner/components/DataRequestForm.vue")['default']>
export const LazyDataRequestsTable: LazyComponent<typeof import("../pages/partner/components/DataRequestsTable.vue")['default']>
export const LazyPartnerForm: LazyComponent<typeof import("../pages/partner/components/PartnerForm.vue")['default']>
export const LazyPartnerTable: LazyComponent<typeof import("../pages/partner/components/PartnerTable.vue")['default']>
export const LazyPatientAppointmentFilters: LazyComponent<typeof import("../pages/patient/appointments/components/PatientAppointmentFilters.vue")['default']>
export const LazyPatientAppointmentForm: LazyComponent<typeof import("../pages/patient/appointments/components/PatientAppointmentForm.vue")['default']>
export const LazyPatientAppointmentsAvailability: LazyComponent<typeof import("../pages/patient/appointments/components/PatientAppointmentsAvailability.vue")['default']>
export const LazyPatientAppointmentsTable: LazyComponent<typeof import("../pages/patient/appointments/components/PatientAppointmentsTable.vue")['default']>
export const LazyPatientsBillingTable: LazyComponent<typeof import("../pages/patient/billing/components/PatientsBillingTable.vue")['default']>
export const LazyDoctorTable: LazyComponent<typeof import("../pages/patient/doctor/components/DoctorTable.vue")['default']>
export const LazyMedicalRecordForm: LazyComponent<typeof import("../pages/patient/medical-records/components/MedicalRecordForm.vue")['default']>
export const LazyMedicalRecordsTable: LazyComponent<typeof import("../pages/patient/medical-records/components/MedicalRecordsTable.vue")['default']>
export const LazyAppointmentFilters: LazyComponent<typeof import("../pages/staff/appointments/components/AppointmentFilters.vue")['default']>
export const LazyAppointmentForm: LazyComponent<typeof import("../pages/staff/appointments/components/AppointmentForm.vue")['default']>
export const LazyAppointmentsAvailability: LazyComponent<typeof import("../pages/staff/appointments/components/AppointmentsAvailability.vue")['default']>
export const LazyAppointmentsTable: LazyComponent<typeof import("../pages/staff/appointments/components/AppointmentsTable.vue")['default']>
export const LazyBillingPaymentForm: LazyComponent<typeof import("../pages/staff/billing/components/BillingPaymentForm.vue")['default']>
export const LazyBillingPaymentInstalmentForm: LazyComponent<typeof import("../pages/staff/billing/components/BillingPaymentInstalmentForm.vue")['default']>
export const LazyBillingPaymentInstalmentTable: LazyComponent<typeof import("../pages/staff/billing/components/BillingPaymentInstalmentTable.vue")['default']>
export const LazyBillingPaymentPlanForm: LazyComponent<typeof import("../pages/staff/billing/components/BillingPaymentPlanForm.vue")['default']>
export const LazyBillingPaymentPlansTable: LazyComponent<typeof import("../pages/staff/billing/components/BillingPaymentPlansTable.vue")['default']>
export const LazyBillingPaymentsTable: LazyComponent<typeof import("../pages/staff/billing/components/BillingPaymentsTable.vue")['default']>
export const LazyBillingTransactionForm: LazyComponent<typeof import("../pages/staff/billing/components/BillingTransactionForm.vue")['default']>
export const LazyBillingTransactionItemForm: LazyComponent<typeof import("../pages/staff/billing/components/BillingTransactionItemForm.vue")['default']>
export const LazyBillingTransactionItemsTable: LazyComponent<typeof import("../pages/staff/billing/components/BillingTransactionItemsTable.vue")['default']>
export const LazyBillingTransactionsTable: LazyComponent<typeof import("../pages/staff/billing/components/BillingTransactionsTable.vue")['default']>
export const LazyAppointmentsList: LazyComponent<typeof import("../pages/staff/dashboard/components/AppointmentsList.vue")['default']>
export const LazyDashboardFilters: LazyComponent<typeof import("../pages/staff/dashboard/components/DashboardFilters.vue")['default']>
export const LazyDashboardSummaryCards: LazyComponent<typeof import("../pages/staff/dashboard/components/DashboardSummaryCards.vue")['default']>
export const LazyDoctorDashboard: LazyComponent<typeof import("../pages/staff/dashboard/components/DoctorDashboard.vue")['default']>
export const LazySecretaryDashboard: LazyComponent<typeof import("../pages/staff/dashboard/components/SecretaryDashboard.vue")['default']>
export const LazyBuildingForm: LazyComponent<typeof import("../pages/staff/facilities/components/BuildingForm.vue")['default']>
export const LazyBuildingsTable: LazyComponent<typeof import("../pages/staff/facilities/components/BuildingsTable.vue")['default']>
export const LazyFacilitiesTable: LazyComponent<typeof import("../pages/staff/facilities/components/FacilitiesTable.vue")['default']>
export const LazyFacilityForm: LazyComponent<typeof import("../pages/staff/facilities/components/FacilityForm.vue")['default']>
export const LazyFacilityLogsTable: LazyComponent<typeof import("../pages/staff/facilities/components/FacilityLogsTable.vue")['default']>
export const LazyInsuranceClaimForm: LazyComponent<typeof import("../pages/staff/insurance/components/InsuranceClaimForm.vue")['default']>
export const LazyInsuranceClaimItemForm: LazyComponent<typeof import("../pages/staff/insurance/components/InsuranceClaimItemForm.vue")['default']>
export const LazyInsuranceClaimItemsTable: LazyComponent<typeof import("../pages/staff/insurance/components/InsuranceClaimItemsTable.vue")['default']>
export const LazyInsuranceClaimsTable: LazyComponent<typeof import("../pages/staff/insurance/components/InsuranceClaimsTable.vue")['default']>
export const LazyInsuranceProviderForm: LazyComponent<typeof import("../pages/staff/insurance/components/InsuranceProviderForm.vue")['default']>
export const LazyInsuranceProviderTable: LazyComponent<typeof import("../pages/staff/insurance/components/InsuranceProviderTable.vue")['default']>
export const LazyEncountersModule: LazyComponent<typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/EncountersModule.vue")['default']>
export const LazyInpatientForm: LazyComponent<typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/InpatientForm.vue")['default']>
export const LazyOutpatientForm: LazyComponent<typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/OutpatientForm.vue")['default']>
export const LazyEncountersTable: LazyComponent<typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/components/EncountersTable.vue")['default']>
export const LazyInpatientTable: LazyComponent<typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/components/InpatientTable.vue")['default']>
export const LazyOutpatientTable: LazyComponent<typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/components/OutpatientTable.vue")['default']>
export const Lazy[inpatientEncounterId]: LazyComponent<typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/inpatient/[inpatientEncounterId].vue")['default']>
export const Lazy[outpatientEncounterId]: LazyComponent<typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/outpatient/[outpatientEncounterId].vue")['default']>
export const LazyNew: LazyComponent<typeof import("../pages/staff/patients/[patientProfileId]/encounters/components/outpatient/new.vue")['default']>
export const LazyAddressFields: LazyComponent<typeof import("../pages/staff/patients/components/AddressFields.vue")['default']>
export const LazyConsentFields: LazyComponent<typeof import("../pages/staff/patients/components/ConsentFields.vue")['default']>
export const LazyContactFields: LazyComponent<typeof import("../pages/staff/patients/components/ContactFields.vue")['default']>
export const LazyEmergencyContactFields: LazyComponent<typeof import("../pages/staff/patients/components/EmergencyContactFields.vue")['default']>
export const LazyEmploymentFields: LazyComponent<typeof import("../pages/staff/patients/components/EmploymentFields.vue")['default']>
export const LazyPatientProfileForm: LazyComponent<typeof import("../pages/staff/patients/components/PatientProfileForm.vue")['default']>
export const LazyPatientProfileTable: LazyComponent<typeof import("../pages/staff/patients/components/PatientProfileTable.vue")['default']>
export const LazyProfileFields: LazyComponent<typeof import("../pages/staff/patients/components/ProfileFields.vue")['default']>
export const LazyPharmacyBrandForm: LazyComponent<typeof import("../pages/staff/pharmacy/components/PharmacyBrandForm.vue")['default']>
export const LazyPharmacyBrandsTable: LazyComponent<typeof import("../pages/staff/pharmacy/components/PharmacyBrandsTable.vue")['default']>
export const LazyPharmacyCategoriesTable: LazyComponent<typeof import("../pages/staff/pharmacy/components/PharmacyCategoriesTable.vue")['default']>
export const LazyPharmacyCategoryForm: LazyComponent<typeof import("../pages/staff/pharmacy/components/PharmacyCategoryForm.vue")['default']>
export const LazyPharmacyItemForm: LazyComponent<typeof import("../pages/staff/pharmacy/components/PharmacyItemForm.vue")['default']>
export const LazyPharmacyItemsTable: LazyComponent<typeof import("../pages/staff/pharmacy/components/PharmacyItemsTable.vue")['default']>
export const LazyPharmacySupplierForm: LazyComponent<typeof import("../pages/staff/pharmacy/components/PharmacySupplierForm.vue")['default']>
export const LazyPharmacySuppliersTable: LazyComponent<typeof import("../pages/staff/pharmacy/components/PharmacySuppliersTable.vue")['default']>
export const LazyStaffForm: LazyComponent<typeof import("../pages/staff/staff/components/StaffForm.vue")['default']>
export const LazyStaffTable: LazyComponent<typeof import("../pages/staff/staff/components/StaffTable.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyUiBreadcrumb: LazyComponent<typeof import("../components/ui/breadcrumb/index")['Breadcrumb']>
export const LazyUiBreadcrumbEllipsis: LazyComponent<typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']>
export const LazyUiBreadcrumbItem: LazyComponent<typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']>
export const LazyUiBreadcrumbLink: LazyComponent<typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']>
export const LazyUiBreadcrumbList: LazyComponent<typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']>
export const LazyUiBreadcrumbPage: LazyComponent<typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']>
export const LazyUiBreadcrumbSeparator: LazyComponent<typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']>
export const LazyUiButton: LazyComponent<typeof import("../components/ui/button/index")['Button']>
export const LazyUiCalendar: LazyComponent<typeof import("../components/ui/calendar/index")['Calendar']>
export const LazyUiCalendarCell: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarCell']>
export const LazyUiCalendarCellTrigger: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarCellTrigger']>
export const LazyUiCalendarGrid: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarGrid']>
export const LazyUiCalendarGridBody: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarGridBody']>
export const LazyUiCalendarGridHead: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarGridHead']>
export const LazyUiCalendarGridRow: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarGridRow']>
export const LazyUiCalendarHeadCell: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarHeadCell']>
export const LazyUiCalendarHeader: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarHeader']>
export const LazyUiCalendarHeading: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarHeading']>
export const LazyUiCalendarNextButton: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarNextButton']>
export const LazyUiCalendarPrevButton: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarPrevButton']>
export const LazyUiCard: LazyComponent<typeof import("../components/ui/card/index")['Card']>
export const LazyUiCardAction: LazyComponent<typeof import("../components/ui/card/index")['CardAction']>
export const LazyUiCardContent: LazyComponent<typeof import("../components/ui/card/index")['CardContent']>
export const LazyUiCardDescription: LazyComponent<typeof import("../components/ui/card/index")['CardDescription']>
export const LazyUiCardFooter: LazyComponent<typeof import("../components/ui/card/index")['CardFooter']>
export const LazyUiCardHeader: LazyComponent<typeof import("../components/ui/card/index")['CardHeader']>
export const LazyUiCardTitle: LazyComponent<typeof import("../components/ui/card/index")['CardTitle']>
export const LazyUiCheckbox: LazyComponent<typeof import("../components/ui/checkbox/index")['Checkbox']>
export const LazyUiCombobox: LazyComponent<typeof import("../components/ui/combobox/index")['Combobox']>
export const LazyUiComboboxAnchor: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxAnchor']>
export const LazyUiComboboxEmpty: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxEmpty']>
export const LazyUiComboboxGroup: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxGroup']>
export const LazyUiComboboxInput: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxInput']>
export const LazyUiComboboxItem: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxItem']>
export const LazyUiComboboxItemIndicator: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxItemIndicator']>
export const LazyUiComboboxList: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxList']>
export const LazyUiComboboxSeparator: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxSeparator']>
export const LazyUiComboboxTrigger: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxTrigger']>
export const LazyUiComboboxViewport: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxViewport']>
export const LazyUiComboboxCancel: LazyComponent<typeof import("../components/ui/combobox/index")['ComboboxCancel']>
export const LazyUiCommand: LazyComponent<typeof import("../components/ui/command/index")['Command']>
export const LazyUiCommandDialog: LazyComponent<typeof import("../components/ui/command/index")['CommandDialog']>
export const LazyUiCommandEmpty: LazyComponent<typeof import("../components/ui/command/index")['CommandEmpty']>
export const LazyUiCommandGroup: LazyComponent<typeof import("../components/ui/command/index")['CommandGroup']>
export const LazyUiCommandInput: LazyComponent<typeof import("../components/ui/command/index")['CommandInput']>
export const LazyUiCommandItem: LazyComponent<typeof import("../components/ui/command/index")['CommandItem']>
export const LazyUiCommandList: LazyComponent<typeof import("../components/ui/command/index")['CommandList']>
export const LazyUiCommandSeparator: LazyComponent<typeof import("../components/ui/command/index")['CommandSeparator']>
export const LazyUiCommandShortcut: LazyComponent<typeof import("../components/ui/command/index")['CommandShortcut']>
export const LazyUiDialog: LazyComponent<typeof import("../components/ui/dialog/index")['Dialog']>
export const LazyUiDialogClose: LazyComponent<typeof import("../components/ui/dialog/index")['DialogClose']>
export const LazyUiDialogContent: LazyComponent<typeof import("../components/ui/dialog/index")['DialogContent']>
export const LazyUiDialogDescription: LazyComponent<typeof import("../components/ui/dialog/index")['DialogDescription']>
export const LazyUiDialogFooter: LazyComponent<typeof import("../components/ui/dialog/index")['DialogFooter']>
export const LazyUiDialogHeader: LazyComponent<typeof import("../components/ui/dialog/index")['DialogHeader']>
export const LazyUiDialogOverlay: LazyComponent<typeof import("../components/ui/dialog/index")['DialogOverlay']>
export const LazyUiDialogScrollContent: LazyComponent<typeof import("../components/ui/dialog/index")['DialogScrollContent']>
export const LazyUiDialogTitle: LazyComponent<typeof import("../components/ui/dialog/index")['DialogTitle']>
export const LazyUiDialogTrigger: LazyComponent<typeof import("../components/ui/dialog/index")['DialogTrigger']>
export const LazyUiDropdownMenu: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']>
export const LazyUiDropdownMenuCheckboxItem: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
export const LazyUiDropdownMenuContent: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']>
export const LazyUiDropdownMenuGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']>
export const LazyUiDropdownMenuItem: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']>
export const LazyUiDropdownMenuLabel: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']>
export const LazyUiDropdownMenuRadioGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
export const LazyUiDropdownMenuRadioItem: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
export const LazyUiDropdownMenuSeparator: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
export const LazyUiDropdownMenuShortcut: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
export const LazyUiDropdownMenuSub: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']>
export const LazyUiDropdownMenuSubContent: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
export const LazyUiDropdownMenuSubTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
export const LazyUiDropdownMenuTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
export const LazyUiDropdownMenuPortal: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']>
export const LazyUiFormControl: LazyComponent<typeof import("../components/ui/form/index")['FormControl']>
export const LazyUiFormDescription: LazyComponent<typeof import("../components/ui/form/index")['FormDescription']>
export const LazyUiFormItem: LazyComponent<typeof import("../components/ui/form/index")['FormItem']>
export const LazyUiFormLabel: LazyComponent<typeof import("../components/ui/form/index")['FormLabel']>
export const LazyUiFormMessage: LazyComponent<typeof import("../components/ui/form/index")['FormMessage']>
export const LazyUiFORMITEMINJECTIONKEY: LazyComponent<typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']>
export const LazyUiForm: LazyComponent<typeof import("../components/ui/form/index")['Form']>
export const LazyUiFormField: LazyComponent<typeof import("../components/ui/form/index")['FormField']>
export const LazyUiFormFieldArray: LazyComponent<typeof import("../components/ui/form/index")['FormFieldArray']>
export const LazyUiInput: LazyComponent<typeof import("../components/ui/input/index")['Input']>
export const LazyUiLabel: LazyComponent<typeof import("../components/ui/label/index")['Label']>
export const LazyUiPopover: LazyComponent<typeof import("../components/ui/popover/index")['Popover']>
export const LazyUiPopoverAnchor: LazyComponent<typeof import("../components/ui/popover/index")['PopoverAnchor']>
export const LazyUiPopoverContent: LazyComponent<typeof import("../components/ui/popover/index")['PopoverContent']>
export const LazyUiPopoverTrigger: LazyComponent<typeof import("../components/ui/popover/index")['PopoverTrigger']>
export const LazyUiSelect: LazyComponent<typeof import("../components/ui/select/index")['Select']>
export const LazyUiSelectContent: LazyComponent<typeof import("../components/ui/select/index")['SelectContent']>
export const LazyUiSelectGroup: LazyComponent<typeof import("../components/ui/select/index")['SelectGroup']>
export const LazyUiSelectItem: LazyComponent<typeof import("../components/ui/select/index")['SelectItem']>
export const LazyUiSelectItemText: LazyComponent<typeof import("../components/ui/select/index")['SelectItemText']>
export const LazyUiSelectLabel: LazyComponent<typeof import("../components/ui/select/index")['SelectLabel']>
export const LazyUiSelectScrollDownButton: LazyComponent<typeof import("../components/ui/select/index")['SelectScrollDownButton']>
export const LazyUiSelectScrollUpButton: LazyComponent<typeof import("../components/ui/select/index")['SelectScrollUpButton']>
export const LazyUiSelectSeparator: LazyComponent<typeof import("../components/ui/select/index")['SelectSeparator']>
export const LazyUiSelectTrigger: LazyComponent<typeof import("../components/ui/select/index")['SelectTrigger']>
export const LazyUiSelectValue: LazyComponent<typeof import("../components/ui/select/index")['SelectValue']>
export const LazyUiSkeleton: LazyComponent<typeof import("../components/ui/skeleton/index")['Skeleton']>
export const LazyUiToaster: LazyComponent<typeof import("../components/ui/sonner/index")['Toaster']>
export const LazyUiTable: LazyComponent<typeof import("../components/ui/table/index")['Table']>
export const LazyUiTableBody: LazyComponent<typeof import("../components/ui/table/index")['TableBody']>
export const LazyUiTableCaption: LazyComponent<typeof import("../components/ui/table/index")['TableCaption']>
export const LazyUiTableCell: LazyComponent<typeof import("../components/ui/table/index")['TableCell']>
export const LazyUiTableEmpty: LazyComponent<typeof import("../components/ui/table/index")['TableEmpty']>
export const LazyUiTableFooter: LazyComponent<typeof import("../components/ui/table/index")['TableFooter']>
export const LazyUiTableHead: LazyComponent<typeof import("../components/ui/table/index")['TableHead']>
export const LazyUiTableHeader: LazyComponent<typeof import("../components/ui/table/index")['TableHeader']>
export const LazyUiTableRow: LazyComponent<typeof import("../components/ui/table/index")['TableRow']>
export const LazyUiTabs: LazyComponent<typeof import("../components/ui/tabs/index")['Tabs']>
export const LazyUiTabsContent: LazyComponent<typeof import("../components/ui/tabs/index")['TabsContent']>
export const LazyUiTabsList: LazyComponent<typeof import("../components/ui/tabs/index")['TabsList']>
export const LazyUiTabsTrigger: LazyComponent<typeof import("../components/ui/tabs/index")['TabsTrigger']>
export const LazyUiTextarea: LazyComponent<typeof import("../components/ui/textarea/index")['Textarea']>
export const LazyUiTooltip: LazyComponent<typeof import("../components/ui/tooltip/index")['Tooltip']>
export const LazyUiTooltipContent: LazyComponent<typeof import("../components/ui/tooltip/index")['TooltipContent']>
export const LazyUiTooltipProvider: LazyComponent<typeof import("../components/ui/tooltip/index")['TooltipProvider']>
export const LazyUiTooltipTrigger: LazyComponent<typeof import("../components/ui/tooltip/index")['TooltipTrigger']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
export const LazyAppICDBrowser: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
